<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jae-Joon Lee">
<meta name="dcterms.date" content="2026-10-09">

<title>tellurix: a differentiable line-by-line telluric model, validated against LBLRTM and applied to IGRINS and FTS atlases</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-3931a3e8aedeb826db45f09b7578f8cf.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="index_files/libs/bootstrap/bootstrap-dark-cfd6df1438725337a6b848ade9423323.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="index_files/libs/bootstrap/bootstrap-3931a3e8aedeb826db45f09b7578f8cf.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#the-forward-model" id="toc-the-forward-model" class="nav-link" data-scroll-target="#the-forward-model">2. The forward model</a>
  <ul class="collapse">
  <li><a href="#light-through-a-layered-atmosphere" id="toc-light-through-a-layered-atmosphere" class="nav-link" data-scroll-target="#light-through-a-layered-atmosphere">2.1 Light through a layered atmosphere</a></li>
  <li><a href="#molecular-absorption-lines" id="toc-molecular-absorption-lines" class="nav-link" data-scroll-target="#molecular-absorption-lines">2.2 Molecular absorption lines</a></li>
  <li><a href="#the-continuum" id="toc-the-continuum" class="nav-link" data-scroll-target="#the-continuum">2.3 The continuum</a></li>
  <li><a href="#from-the-sky-to-the-detector" id="toc-from-the-sky-to-the-detector" class="nav-link" data-scroll-target="#from-the-sky-to-the-detector">2.4 From the sky to the detector</a></li>
  <li><a href="#implementation-side-by-side-with-lblrtm" id="toc-implementation-side-by-side-with-lblrtm" class="nav-link" data-scroll-target="#implementation-side-by-side-with-lblrtm">2.5 Implementation, side by side with LBLRTM</a></li>
  <li><a href="#line-shape-evaluation-and-line-rejection" id="toc-line-shape-evaluation-and-line-rejection" class="nav-link" data-scroll-target="#line-shape-evaluation-and-line-rejection">2.6 Line-shape evaluation and line rejection</a></li>
  <li><a href="#layering-and-continuum" id="toc-layering-and-continuum" class="nav-link" data-scroll-target="#layering-and-continuum">2.7 Layering and continuum</a></li>
  <li><a href="#line-coupling" id="toc-line-coupling" class="nav-link" data-scroll-target="#line-coupling">2.8 Line coupling</a></li>
  <li><a href="#instrument-model" id="toc-instrument-model" class="nav-link" data-scroll-target="#instrument-model">2.9 Instrument model</a></li>
  <li><a href="#numerics-that-make-it-fast-and-differentiable" id="toc-numerics-that-make-it-fast-and-differentiable" class="nav-link" data-scroll-target="#numerics-that-make-it-fast-and-differentiable">2.10 Numerics that make it fast and differentiable</a></li>
  </ul></li>
  <li><a href="#fitting-and-computational-cost" id="toc-fitting-and-computational-cost" class="nav-link" data-scroll-target="#fitting-and-computational-cost">3. Fitting and computational cost</a>
  <ul class="collapse">
  <li><a href="#the-fitter" id="toc-the-fitter" class="nav-link" data-scroll-target="#the-fitter">3.1 The fitter</a></li>
  <li><a href="#where-the-time-goes" id="toc-where-the-time-goes" class="nav-link" data-scroll-target="#where-the-time-goes">3.2 Where the time goes</a></li>
  <li><a href="#against-lblrtm-stage-by-stage" id="toc-against-lblrtm-stage-by-stage" class="nav-link" data-scroll-target="#against-lblrtm-stage-by-stage">3.3 Against LBLRTM, stage by stage</a></li>
  <li><a href="#uncertainties" id="toc-uncertainties" class="nav-link" data-scroll-target="#uncertainties">3.4 Uncertainties</a></li>
  </ul></li>
  <li><a href="#validation-against-lblrtm" id="toc-validation-against-lblrtm" class="nav-link" data-scroll-target="#validation-against-lblrtm">4. Validation against LBLRTM</a>
  <ul class="collapse">
  <li><a href="#figures" id="toc-figures" class="nav-link" data-scroll-target="#figures">4.1 Figures</a></li>
  </ul></li>
  <li><a href="#application-to-fts-atlases" id="toc-application-to-fts-atlases" class="nav-link" data-scroll-target="#application-to-fts-atlases">5. Application to FTS atlases</a>
  <ul class="collapse">
  <li><a href="#instrument-profile-measured-from-the-spectrum" id="toc-instrument-profile-measured-from-the-spectrum" class="nav-link" data-scroll-target="#instrument-profile-measured-from-the-spectrum">5.1 Instrument profile measured from the spectrum</a></li>
  <li><a href="#arcturus-hinkle-wallace-livingston-1995" id="toc-arcturus-hinkle-wallace-livingston-1995" class="nav-link" data-scroll-target="#arcturus-hinkle-wallace-livingston-1995">5.2 Arcturus (Hinkle, Wallace &amp; Livingston 1995)</a></li>
  <li><a href="#nso-kitt-peak-solar-atlases" id="toc-nso-kitt-peak-solar-atlases" class="nav-link" data-scroll-target="#nso-kitt-peak-solar-atlases">5.3 NSO Kitt Peak solar atlases</a></li>
  <li><a href="#figures-1" id="toc-figures-1" class="nav-link" data-scroll-target="#figures-1">5.4 Figures</a></li>
  </ul></li>
  <li><a href="#application-to-igrins" id="toc-application-to-igrins" class="nav-link" data-scroll-target="#application-to-igrins">6. Application to IGRINS</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">6.1 Data</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">6.2 Method</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">6.3 Results</a></li>
  <li><a href="#known-limitations" id="toc-known-limitations" class="nav-link" data-scroll-target="#known-limitations">6.4 Known limitations</a></li>
  <li><a href="#figures-2" id="toc-figures-2" class="nav-link" data-scroll-target="#figures-2">6.5 Figures</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">7. Discussion</a></li>
  <li><a href="#summary-software-and-data-availability" id="toc-summary-software-and-data-availability" class="nav-link" data-scroll-target="#summary-software-and-data-availability">8. Summary; software and data availability</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">tellurix: a differentiable line-by-line telluric model, validated against LBLRTM and applied to IGRINS and FTS atlases</h1>
<p class="subtitle lead">Working draft for the Astronomical Journal</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jae-Joon Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This page is generated from the working draft; numbers and figures may change before submission.</p>
</div>
</div>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>We present tellurix, a differentiable forward model of terrestrial atmospheric absorption for high-resolution spectra, built on JAX and ExoJAX. It combines line-by-line Voigt opacity from the AER line file, the MT_CKD 4.3 water continuum, a layered atmosphere from ERA5 or standard profiles, and an instrument model with a Gaussian or FTS line-spread function. A bounded maximum a posteriori fitter uses exact gradients. Evaluating only line–sample pairs that can reach the Voigt core, linearizing the opacity in the one fitted quantity that enters it, and compiling once per spectral order make a staged fit 18× faster, taking 3.3 s on one GPU. Given identical atmospheric layers, the fitted transmission agrees with LBLRTM 12.17 to 0.010% median and 0.039% at the 99th percentile at R = 45,000, once first-order CO2 line coupling is included. We correct the full Arcturus infrared atlas (598 page-epochs, 0.91–5.4 µm) and NSO Kitt Peak solar atlases, measuring each spectrum’s instrumental profile from its own interferogram envelope. In both, the residual floor of about 1% comes from the stellar model, not the telluric one. On IGRINS A0V standards from three sites, H and K orders fit to about 1.3σ on a dry night. A night calibration then corrects held-out stars to 0.3–0.5× noise in absorbing orders with one water scale and one velocity per frame. A per-night systematic in the dry-gas columns is traced to header air masses describing only the first exposure of a sequence. The code and all fitted products are public.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>The introduction argues one point: telluric correction needs a forward model that is accurate, differentiable and fast enough to fit every order of every frame. Today no single code is all three. Planned paragraphs:</p>
<ol type="1">
<li><strong>The problem.</strong> Ground-based near-infrared spectra at R ~ 45,000 (IGRINS H and K) carry H2O, CO2, CH4, N2O, CO and O2 absorption at the percent-to-saturated level. Correction by an observed A0V standard transfers its errors: the standard’s own lines, an air-mass and time mismatch, and changes in water.</li>
<li><strong>Synthetic correction today.</strong> TelFit (Gullikson et al.&nbsp;2014) and molecfit (Smette et al.&nbsp;2015; Kausch et al.&nbsp;2015) wrap LBLRTM in a derivative-free or finite-difference optimizer. Each fit re-runs LBLRTM, so cost scales with the number of evaluations, and the model cannot share a gradient with a stellar fit.</li>
<li><strong>Differentiable radiative transfer.</strong> ExoJAX (Kawahara et al.&nbsp;2022, 2025) gives line-by-line opacity in JAX with autodiff on GPUs. It targets exoplanet and brown-dwarf atmospheres, not a layered Earth atmosphere seen along a slant path at an instrument’s resolution.</li>
<li><strong>This paper.</strong> tellurix couples ExoJAX opacity to a layered terrestrial atmosphere, the MT_CKD 4.3 water continuum, AER Line File 3.9, an instrument model and a bounded MAP fitter. LBLRTM 12.17 serves as the regression reference, not the runtime. We validate it against LBLRTM, then apply it to three kinds of data: the Arcturus FTS atlas, the NSO Kitt Peak solar atlases and IGRINS A0V standards from three sites.</li>
<li><strong>Outline</strong> of the remaining sections.</li>
</ol>
</section>
<section id="the-forward-model" class="level2">
<h2 class="anchored" data-anchor-id="the-forward-model">2. The forward model</h2>
<p>A ground-based spectrum is the star’s light multiplied by the transmission of Earth’s atmosphere and then blurred and sampled by the spectrograph. To remove the atmosphere we model it: we write down, from physics, the spectrum the instrument <em>should</em> record for a given atmosphere, star and instrument. This is called a <strong>forward model</strong>. We then adjust the model’s few free parameters, such as the amount of water vapour, until the prediction matches the data. Once it does, dividing the data by the fitted atmospheric transmission leaves the star.</p>
<p>This chapter builds that forward model in the order light meets it:</p>
<ul>
<li><strong>Absorption along the path (2.1).</strong> Light passes through a layered atmosphere and loses intensity by absorption.</li>
<li><strong>Molecular lines (2.2).</strong> Most of that absorption happens in narrow lines, each with a strength and a shape.</li>
<li><strong>The continuum (2.3).</strong> A smooth component that individual lines miss.</li>
<li><strong>The instrument (2.4).</strong> The spectrograph smears and samples the result.</li>
<li><strong>Implementation (2.5–2.10).</strong> How tellurix computes all of this quickly enough to fit, and with derivatives, compared step by step with LBLRTM, the reference code of the field.</li>
</ul>
<p>The symbols used throughout the chapter:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
<th>Typical unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ν</td>
<td>wavenumber, 1/λ; spectroscopists’ unit of frequency</td>
<td>cm−1 (5000 cm−1 = 2.0 µm)</td>
</tr>
<tr class="even">
<td>I, I₀</td>
<td>intensity after and before absorption</td>
<td>any</td>
</tr>
<tr class="odd">
<td>T(ν)</td>
<td>transmission, I/I₀, between 0 and 1</td>
<td>—</td>
</tr>
<tr class="even">
<td>τ(ν)</td>
<td>optical depth, −ln T</td>
<td>—</td>
</tr>
<tr class="odd">
<td>σ(ν)</td>
<td>absorption cross-section per molecule</td>
<td>cm²</td>
</tr>
<tr class="even">
<td>N</td>
<td>column density: molecules per unit area along the path</td>
<td>cm−2</td>
</tr>
<tr class="odd">
<td>S</td>
<td>line strength (integrated cross-section of one line)</td>
<td>cm−1/(molecule cm−2)</td>
</tr>
<tr class="even">
<td>ν₀</td>
<td>line centre</td>
<td>cm−1</td>
</tr>
<tr class="odd">
<td>α_D, α_L, α_V</td>
<td>Doppler, Lorentz (pressure) and Voigt half-widths of a line</td>
<td>cm−1</td>
</tr>
<tr class="even">
<td>P, T_k, P_self</td>
<td>pressure, temperature, partial pressure of the absorbing gas itself</td>
<td>bar or atm, K</td>
</tr>
<tr class="odd">
<td>z</td>
<td>zenith angle: the angle between the line of sight and vertical</td>
<td>degrees</td>
</tr>
<tr class="even">
<td>X = 1/cos z</td>
<td>air mass: path length relative to looking straight up</td>
<td>—</td>
</tr>
<tr class="odd">
<td>s</td>
<td>fitted column scale of one gas, relative to the model atmosphere</td>
<td>—</td>
</tr>
<tr class="even">
<td>R = λ/Δλ</td>
<td>resolving power of the spectrograph</td>
<td>45,000 for IGRINS</td>
</tr>
</tbody>
</table>
<section id="light-through-a-layered-atmosphere" class="level3">
<h3 class="anchored" data-anchor-id="light-through-a-layered-atmosphere">2.1 Light through a layered atmosphere</h3>
<p><strong>Absorption along a path.</strong> When light of intensity I crosses a thin slab containing n absorbing molecules per cm³, each with cross-section σ (the effective area it blocks), a fraction σn ds is removed over a length ds: dI = −I σ n ds. Integrating gives the Beer–Lambert law,</p>
<p><span class="math display">\[
I(\nu) = I_0(\nu)\,e^{-\tau(\nu)}, \qquad \tau(\nu) = \int \sigma(\nu)\, n\, ds = \sigma(\nu)\,N
\]</span></p>
<p>Here τ is the <strong>optical depth</strong> and N = ∫n ds is the <strong>column density</strong>: the number of molecules in a 1 cm² tube along the line of sight. Optical depths of different gases add, so their transmissions multiply. Everything that depends on wavenumber sits in σ(ν), and most of the next section is about computing it.</p>
<p><strong>Why layers.</strong> The atmosphere is not uniform:</p>
<ul>
<li>Pressure falls roughly exponentially with height, by a factor e about every 8 km.</li>
<li>Temperature changes by tens of kelvin between the ground and the stratosphere.</li>
<li>Water vapour is concentrated in the lowest few kilometres.</li>
</ul>
<p>Because σ itself depends on pressure and temperature (Section 2.2), the integral cannot be done with one σ. We therefore cut the atmosphere into layers ℓ, typically 12, each with a single pressure, temperature and composition, and sum their contributions. Choosing those layer values well is a numerical question of its own (Section 2.7).</p>
<p><strong>Air mass.</strong> A star observed at zenith angle z is seen through a path longer than the vertical one by 1/cos z, called the <strong>air mass</strong> X. Treating the layers as flat (plane-parallel), which is accurate except close to the horizon, the transmission of the whole path is</p>
<p><span class="math display">\[
T(\nu) = \exp\Big[-\frac{1}{\cos z}\sum_{\ell}\Big(\sum_{\rm gas} s_{\rm gas}\,N_{{\rm gas},\ell}\;\sigma_{\rm gas}(\nu;P_\ell,T_\ell,P_{{\rm self},\ell}) + \tau^{\rm cont}_\ell(\nu)\Big)\Big]
\]</span></p>
<p><img src="figures/diagrams/light_path.png" class="img-fluid" style="width:100.0%" alt="schematic · plane-parallel layered atmosphere, as in TelluricModel.transmission"></p>
<p><strong>Where the atmosphere comes from.</strong> Pressure, temperature and composition at the site and time of an observation come from ERA5, a global weather reanalysis, or from standard AFGL model atmospheres. The water content changes from hour to hour, and well-mixed gases such as CO2 and CH4 drift slowly. Each gas’s column is therefore multiplied by a free <strong>column scale</strong> s_gas, fitted to the data. tellurix keeps the layers top to bottom, with pressure increasing downward (<code>AtmosphereProfile</code>, <code>site_profile.py</code>, <code>tellurix.era5</code>).</p>
</section>
<section id="molecular-absorption-lines" class="level3">
<h3 class="anchored" data-anchor-id="molecular-absorption-lines">2.2 Molecular absorption lines</h3>
<p><strong>What a line is.</strong> A molecule can only absorb a photon whose energy matches the difference between two of its quantized energy levels. In the near infrared these are mostly vibration–rotation transitions: a change in how the atoms vibrate, together with a change in how fast the molecule rotates. Each transition absorbs at its own wavenumber ν₀, called a <strong>line</strong>. Molecules have many rotational levels, so every vibrational change produces a <strong>band</strong> of hundreds to thousands of lines. Examples are the water bands at 1.4 and 1.9 µm and the CO2 bands at 1.6 and 2.0 µm (Figure 2.4). The positions, strengths and broadening coefficients of these lines are measured in laboratories and compiled in line lists such as HITRAN. tellurix uses AER Line File 3.9, the list LBLRTM uses.</p>
<p>The cross-section of one line is its integrated strength S times a normalized shape function f:</p>
<p><span class="math display">\[
\sigma(\nu) = S(T)\, f(\nu - \nu_0;\, \alpha_D, \alpha_L), \qquad \int f\, d\nu = 1
\]</span></p>
<p>The total σ is the sum over every line of the gas.</p>
<p><strong>Strength depends on temperature.</strong> A line absorbs only from molecules in its lower energy level E″, and how many sit there follows the Boltzmann distribution. Line lists give S at T_ref = 296 K, and it is scaled to the layer temperature with the partition function Q(T) and the second radiation constant c₂ = hc/k = 1.4388 cm K:</p>
<p><span class="math display">\[
S(T) = S(T_{\rm ref})\,\frac{Q(T_{\rm ref})}{Q(T)}\,\exp\!\Big[-c_2 E''\Big(\frac{1}{T}-\frac{1}{T_{\rm ref}}\Big)\Big]\,\frac{1-e^{-c_2\nu_0/T}}{1-e^{-c_2\nu_0/T_{\rm ref}}}
\]</span></p>
<p>Lines from high-lying levels weaken quickly in cold layers. That is one reason the vertical temperature profile matters.</p>
<p><strong>Shape: two broadening mechanisms.</strong></p>
<ul>
<li><strong>Doppler broadening.</strong> Molecules move thermally along the line of sight, so each sees the light Doppler-shifted. This gives a Gaussian profile of half-width α_D = (ν₀/c)√(2 ln 2 kT/m). For water at 2 µm, α_D ≈ 0.007 cm−1.</li>
<li><strong>Pressure (collisional) broadening.</strong> Collisions interrupt the molecule while it absorbs. This gives a Lorentzian profile of half-width α_L = (γ_air · (P − P_self) + γ_self · P_self) · (T_ref / T)ⁿ, proportional to pressure. Near the ground α_L ≈ 0.07 cm−1, ten times the Doppler width. Above about 20 km (57 hPa), Doppler broadening dominates (Figure 2.2).</li>
<li><strong>The Voigt profile.</strong> Both act at once, so the true shape is their convolution, the Voigt profile. It has no closed form. It is computed from the complex Faddeeva function w(z): the Voigt profile is proportional to Re w(x + ia), with x the distance from line centre and a the ratio of the Lorentz to Doppler widths, both in units of the Doppler width. Evaluating w accurately and quickly is the computational heart of the problem.</li>
</ul>
<p><strong>Wings and why the calculation is expensive.</strong> Far from its centre a Lorentzian falls only as 1/(ν − ν₀)², so a strong line still absorbs measurably tens of cm−1 away. A model of one spectral window must therefore include every line within a 25 cm−1 margin around it. For one IGRINS K order this means about 13,000 lines, 2,800 spectral samples and 12 layers: roughly 4 × 10⁸ evaluations of w for a single model spectrum. Sections 2.6 and 2.10 explain how the two codes make this affordable.</p>
<p><strong>Two refinements.</strong></p>
<ul>
<li><strong>Pressure shift.</strong> Collisions also shift each line centre slightly, by δ_air × P, typically 0.01 cm−1 per atmosphere. Both codes apply it; tellurix makes it optional.</li>
<li><strong>Line coupling (line mixing).</strong> When neighbouring lines overlap at high pressure, collisions transfer intensity between them. To first order this adds a small antisymmetric term to each line, proportional to a coupling coefficient Y times pressure (Section 2.8). It matters for the dense CO2 bands at 2.0 and 1.6 µm.</li>
</ul>
<p><img src="figures/output/fig_intro_lineshape.png" class="img-fluid" style="width:100.0%" alt="line shape anatomy"></p>
<p><strong>Figure 2.2. How one water line gets its shape and strength</strong> (H2O at 5004.585 cm−1, AER 3.9, in each layer of an ERA5 atmosphere over Gemini South).</p>
<ul>
<li><strong>(a) Widths against height.</strong> The Doppler width barely changes (0.006–0.007 cm−1), while the pressure width falls with pressure, from 0.065 cm−1 in the lowest layer. The two are equal at 57 hPa, about 20 km: below that, pressure broadening dominates the line; above it, Doppler does. The dotted line marks half of IGRINS’s resolution element, so lines from the lowest layers are about as wide as what the spectrograph can resolve.</li>
<li><strong>(b) The profile in four layers.</strong> Near the ground the Voigt profile is essentially Lorentzian. In the stratosphere its core is Gaussian, but its far wings are still Lorentzian, falling as 1/(ν − ν₀)², and it is those wings that make far-away lines matter.</li>
<li><strong>(c) Temperature.</strong> A line from a low-lying level (E″ = 135 cm−1) strengthens slightly in cold air. One from a high level (E″ = 1813 cm−1) weakens by an order of magnitude over the temperatures of this atmosphere, which is why each layer’s temperature enters the calculation.</li>
</ul>
</section>
<section id="the-continuum" class="level3">
<h3 class="anchored" data-anchor-id="the-continuum">2.3 The continuum</h3>
<p>Adding up individual Voigt lines does not reproduce all the absorption measured in the laboratory or in the field. A smooth extra component, varying over hundreds of cm−1, remains. This is the <strong>continuum</strong>. For water it has two parts:</p>
<ul>
<li>the <strong>self continuum</strong>, from water molecules colliding with each other, proportional to the square of the water density;</li>
<li>the <strong>foreign continuum</strong>, from water colliding with N2 and O2, proportional to water density times air density.</li>
</ul>
<p>Its physical origin is still debated: far line wings that are not exactly Lorentzian, and short-lived water dimers, both contribute. In practice it is modelled semi-empirically. MT_CKD (Mlawer et al.&nbsp;2012, 2023) tabulates coefficients fitted to measurements on a 10 cm−1 grid, and both codes use the same version 4.3.</p>
<p>One convention matters for consistency with the lines. MT_CKD is defined as what remains once every line has been cut at 25 cm−1 from its centre and its value at the cut has been subtracted (the “pedestal”). LBLRTM shapes its lines exactly that way. tellurix keeps the full Voigt wing, so the two descriptions overlap slightly. The overlap is smooth over a spectral order, and the fitted continuum of Section 2.4 absorbs it (Sections 2.6 and 4).</p>
<p>The water continuum is weak inside the IGRINS bands: a mean optical depth of about 0.003 at 2.0 µm on a dry night. It is strongest in the opaque 1.9 µm water band between H and K (Figure 2.7b). Its importance is that it is smooth across an entire order, where a bias would otherwise mimic a wrong column. For the solar spectra tellurix also includes the collision-induced absorption of O2 (O2–O2 and O2–N2 pairs), ported from LBLRTM. It changes the spectrum near 1.27 µm by up to 9%.</p>
</section>
<section id="from-the-sky-to-the-detector" class="level3">
<h3 class="anchored" data-anchor-id="from-the-sky-to-the-detector">2.4 From the sky to the detector</h3>
<p>The atmosphere’s transmission is not what the detector records. Four more steps connect it to the data.</p>
<p><strong>1. The star.</strong> The light entering the atmosphere is the star’s own spectrum F★(ν), with its own absorption lines. Telluric lines stay fixed in the observatory’s frame. Stellar lines are Doppler-shifted by the star’s radial velocity and by Earth’s orbital motion, which changes by up to ±30 km/s over a year. This difference is what lets the two be separated. tellurix multiplies the transmission by a synthetic stellar spectrum from The Payne Zero (an A0V star for IGRINS standards, the Sun or Arcturus for the atlases), shifted by a fitted stellar velocity (<code>stellar.py</code>).</p>
<p><strong>2. Finite resolution.</strong> A spectrograph cannot separate features closer than about Δλ = λ/R, where R is its <strong>resolving power</strong>. Its output is the true spectrum convolved with the <strong>line-spread function</strong> (LSF), the response to an infinitely narrow line. Two kinds of instrument are treated:</p>
<ul>
<li><strong>IGRINS</strong>, a slit-fed echelle spectrograph with R ≈ 45,000, whose LSF is close to a Gaussian 6.7 km/s wide (FWHM).</li>
<li><strong>Fourier-transform spectrometers (FTS)</strong>, which made the solar and Arcturus atlases. An FTS measures an interferogram up to a maximum optical path difference L and Fourier-transforms it. Cutting the interferogram at L makes the LSF a sinc function, sin(x)/x, whose width is set by L. That sinc has slowly decaying side lobes, and how they are handled matters (Section 2.9).</li>
</ul>
<p>Telluric lines at R = 45,000 are only partly resolved: a typical water line, 0.15 cm−1 wide, spans about one resolution element. That is why the model is computed on a grid four times finer than the instrument’s resolution and then convolved.</p>
<p><strong>3. Pixels and wavelengths.</strong> Each detector pixel collects light over a finite wavelength range. The model integrates over each pixel with Simpson’s rule rather than sampling its centre (an FTS samples points, so there it is switched off). The pipeline’s wavelength solution can be off by a fraction of a pixel, so a velocity shift and a small linear stretch are fitted.</p>
<p><strong>4. The continuum level.</strong> The echelle’s blaze function, the flat field and the star’s slope multiply the spectrum by a smooth function. It is modelled as the exponential of a low-order Chebyshev polynomial, with fitted coefficients.</p>
<p>Putting the steps together, the model flux in pixel i is</p>
<p><span class="math display">\[
F_i = \exp\Big(\sum_k c_k\,T_k(x_i)\Big)\;\frac{1}{\Delta\lambda_i}\int_{\rm pixel\ i}\big[(F_\star\cdot T)\otimes{\rm LSF}\big](\lambda)\,d\lambda
\]</span></p>
<p>Here T_k are Chebyshev polynomials and x_i is the pixel position scaled to [−1, 1]. The free parameters of a fit are few:</p>
<ul>
<li>one column scale per absorbing gas;</li>
<li>the telluric and stellar velocities and the wavelength stretch;</li>
<li>the LSF width;</li>
<li>the continuum coefficients;</li>
<li>an extra noise term (“jitter”).</li>
</ul>
<p><strong>What the model produces.</strong> The figures below are the transmission of one real atmosphere: ERA5 over Gemini South on 2021-03-17, 4.3 mm of precipitable water, air mass 1.5. They come from the full line-by-line calculation at IGRINS sampling: about 1.3 million lines of seven gases, with the water continuum and O2 collision-induced absorption.</p>
<p><img src="figures/output/fig_intro_transmission_overview.png" class="img-fluid" style="width:100.0%" alt="sky transmission 0.9-5.3 um"></p>
<p><strong>Figure 2.4a. The near-infrared sky, 0.9–5.3 µm, smoothed to R = 2,000.</strong> Absorption bands of water, CO2 and CH4 divide the spectrum into the familiar J, H, K, L′ and M′ windows (grey). Even inside the windows the sky is far from transparent. IGRINS covers H and K (blue bars).</p>
<p><img src="figures/output/fig_intro_transmission.png" class="img-fluid" style="width:100.0%" alt="H and K by molecule"></p>
<p><strong>Figure 2.4b. H and K at IGRINS resolution, and who absorbs what.</strong></p>
<ul>
<li><strong>(b) All gases together, R = 45,000.</strong> H is mostly clear, with mean transmission 0.94 and 13% of samples below 0.9. K is much harder, with mean 0.83 and 41% of samples below 0.9.</li>
<li><strong>(c) One gas at a time:</strong>
<ul>
<li>water, with its continuum, closes the gaps between the bands;</li>
<li>CO2 saturates at 2.0 µm and absorbs up to 50% at 1.57 and 1.60 µm;</li>
<li>CH4 fills the red half of K, with its deepest line 81% deep at 2.3 µm;</li>
<li>N2O and CO are weak, at most 6–7% (their rows are magnified);</li>
<li>O2 and O3 absorb under 1% anywhere in H and K.</li>
</ul></li>
<li><strong>(d) A 2 nm zoom at 2.318 µm.</strong> The grey curve is the atmosphere at infinite resolution; the black curve is what the spectrograph records. The deepest line reaches 0.17 but appears only as 0.52 after the line-spread function. Fitting at the instrument’s resolution therefore depends on a correct LSF as much as on correct lines.</li>
</ul>
<p><img src="figures/diagrams/model_composition.png" class="img-fluid" style="width:100.0%" alt="F1 draft · model composition, from model.py and fit.py"></p>
<p>The whole model at a glance. The four inputs on the left (atmosphere, line opacity, continuum and an optional LBLRTM correction template) are interchangeable components, so tests can run without spectroscopic data. They produce the transmission, which the observation model turns into pixel fluxes (Section 2.4), and a bounded fit adjusts the parameters using exact gradients (Section 2.5).</p>
</section>
<section id="implementation-side-by-side-with-lblrtm" class="level3">
<h3 class="anchored" data-anchor-id="implementation-side-by-side-with-lblrtm">2.5 Implementation, side by side with LBLRTM</h3>
<p>Before comparing the two codes, here is what a modern fitting code needs, briefly.</p>
<p><strong>Fitting needs gradients.</strong> A fit adjusts the parameters θ to minimize χ²(θ) = Σ_i (data_i − model_i)²/σ_i². The most efficient optimizers use the gradient ∂χ²/∂θ, which says which way is downhill. tellurix uses L-BFGS-B, which also builds up an estimate of the curvature from successive gradients and respects parameter bounds. Each iteration needs χ² and its gradient.</p>
<p><strong>Two ways to get a gradient.</strong></p>
<ul>
<li><strong>Finite differences.</strong> Nudge each parameter by a small step h and rerun the model: P + 1 runs for P parameters, or 2P + 1 for the more accurate central difference. The answer depends on h. Too large a step gives truncation error; too small a step loses the difference in rounding error (Figure 2.10d). An LBLRTM-based fit has no other option, because LBLRTM computes only spectra.</li>
<li><strong>Automatic differentiation (autodiff).</strong> A program, however long, is a chain of elementary operations (add, multiply, exp, …), each with a known derivative. An autodiff system applies the chain rule through that chain mechanically, giving derivatives exact to rounding error with no step to choose. In <strong>reverse mode</strong> (back-propagation, as used to train neural networks), the gradient of one number such as χ² with respect to <em>all</em> parameters costs a single backward pass. That pass costs a few times one model evaluation, whatever the number of parameters.</li>
</ul>
<p><strong>JAX, compilation and GPUs.</strong> tellurix is written in JAX, a Python library with a NumPy-like interface:</p>
<ul>
<li><code>jax.grad</code> turns a function into one that returns its gradient.</li>
<li><code>jax.jit</code> traces the function once and compiles it, through the XLA compiler, into fused machine code for a CPU or a GPU. Compilation takes seconds, but each later call takes milliseconds, so a fit should compile once and reuse the result (Section 3).</li>
<li><code>jax.vmap</code> vectorizes a function, for example over atmospheric layers.</li>
</ul>
<p>A GPU has thousands of simple arithmetic units. The line-by-line calculation is the same arithmetic repeated over roughly 10⁸ independent line–sample pairs, which suits it ideally. GPUs are fastest in single precision, which motivates the mixed-precision scheme of Section 2.10.</p>
<p><strong>The price.</strong> Compiled, differentiable code must be written as operations on whole arrays of fixed shape. An <code>if</code> statement whose outcome differs from element to element is usually computed both ways, with the unwanted result discarded. Several of tellurix’s techniques (Section 2.10) exist to avoid that waste. The Voigt opacity itself comes from ExoJAX (Kawahara et al.&nbsp;2022), a JAX code for exoplanet atmospheres, and tellurix builds the terrestrial model around it.</p>
<p>tellurix computes the same physics as LBLRTM, stage for stage, but it changes three things about how that physics is executed:</p>
<ol type="1">
<li>It evaluates every line exactly rather than approximating cheaply.</li>
<li>It puts all layers on one grid, so there is no merge step.</li>
<li>It keeps the whole chain from opacity to detector pixels inside one compiled function that JAX can differentiate.</li>
</ol>
<p>Sections 2.6–2.10 compare each stage, with LBLRTM routines cited from its 12.17 source.</p>
<p><img src="figures/diagrams/pipelines.png" class="img-fluid" style="width:100.0%" alt="pipelines · LBLRTM from lblrtm.f90, oprop.f90, xmerge.f90, postsub.f90; tellurix from model.py, direct.py"></p>
<p>LBLRTM passes files between stages: TAPE3, TAPE10 per layer and TAPE12. Its output stops at a scanned spectrum, so a fit has to rerun it. In tellurix, rows 3–6 are one compiled function, and its gradient comes from the same call.</p>
</section>
<section id="line-shape-evaluation-and-line-rejection" class="level3">
<h3 class="anchored" data-anchor-id="line-shape-evaluation-and-line-rejection">2.6 Line-shape evaluation and line rejection</h3>
<p><em>In plain terms.</em> Section 2.2 showed that a model spectrum needs the Voigt profile of every line at every spectral sample, about 10⁸ times. Near a line’s centre the Faddeeva function needs a careful, comparatively slow algorithm; tellurix uses Algorithm 916 of Zaghloul &amp; Ali (2011). Far from the centre (large x) a short asymptotic series, w(z) ≈ (i/√π)(1/z + 1/(2z³) + 3/(4z⁵) + …), is accurate and cheap. A code can save time in two ways:</p>
<ol type="1">
<li>Evaluate the expensive part only where it is needed. LBLRTM does this by splitting each line into pieces stored on grids of different spacing; tellurix by choosing, pair by pair, which formula to use.</li>
<li>Skip lines too weak to matter. LBLRTM does this by default; tellurix does not.</li>
</ol>
<p>Below, “grid” means the set of wavenumbers at which the spectrum is computed, and DV its spacing.</p>
<p>LBLRTM makes each line cheap by splitting it into four pieces on progressively coarser grids, and by dropping weak lines. tellurix evaluates the exact Voigt at every grid point and keeps every line; the sparse core keeps that affordable (Section 2.10). Both reach the same core, and they differ in the far wing at the 1e−5 level.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>LBLRTM 12.17 (<code>oprop.f90</code>)</th>
<th>tellurix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Line profile</td>
<td>Four sub-functions: F1–F3 out to 4, 16 and 64 α_V on grids DV, 4DV and 16DV (HIRAC1/CNVFNV, 168–1349), and F4 from 64 α_V to 25 cm−1 on 64DV (LBLF4/CONVF4, 3938–4010), joined by 4-point Lagrange (PANEL) and cubic (XINT) interpolation</td>
<td>Exact Voigt (ExoJAX <code>hjert</code>): Algorithm 916 where x² + a² &lt; 111, asymptotic series elsewhere, at every grid point of a constant-velocity grid</td>
</tr>
<tr class="even">
<td>Lookup</td>
<td>Pre-tabulated shapes, nearest node (1313–1319)</td>
<td>Evaluated directly</td>
</tr>
<tr class="odd">
<td>Cutoff</td>
<td>25 cm−1, less a pedestal; CO2 uses (2 − x²/B²) L(B) (3956); χ forced to 1 (4075)</td>
<td>None: every line within the 25 cm−1 selection margin, full wing</td>
</tr>
<tr class="even">
<td>Weak lines</td>
<td>Rejected per layer when S·N/α_V ≤ DPTMIN + DPTFAC·R4 (2e−4, 1e−3; 1153–1171, 3900–3917); coupled lines exempt</td>
<td>All kept; optional <code>select_significant_lines</code> with a guaranteed error bound</td>
</tr>
<tr class="odd">
<td>Grid</td>
<td>Per layer, DV from the mean Voigt width of a nominal line (0.0014–0.0077 cm−1 here)</td>
<td>One grid for all layers (0.028 cm−1 at R = 45,000 × 4)</td>
</tr>
</tbody>
</table>
<p><img src="figures/output/fig_method_lineshape.png" class="img-fluid" style="width:100.0%" alt="line shape"></p>
<p><strong>Figure 2.6a. One H2O line (5004.585 cm−1, 800 hPa, 280 K) in both codes.</strong> (a) LBLRTM’s four sub-functions and their sum, compared with its own output (circles). (b) tellurix’s branches: Algorithm 916 within 0.051 cm−1, the core list within 0.147 cm−1, the asymptotic series beyond, with no cutoff. (c) The core, where both sample the same Voigt. (d) Departure from the exact Voigt: LBLRTM reaches 8e−4 of the peak in the core from table lookup, then levels off at the pedestal (8.7e−6 of the peak); tellurix stays below 2.4e−8.</p>
<p><img src="figures/output/fig_method_rejection.png" class="img-fluid" style="width:100.0%" alt="rejection"></p>
<p><strong>Figure 2.6b. LBLRTM’s line rejection, bottom layer of the ERA5 profile, 5000–5020 cm−1.</strong></p>
<ul>
<li><ol type="a">
<li>HIRAC1 keeps 372 of the 4207 lines it tests: 90% are rejected.</li>
</ol></li>
<li><ol start="2" type="a">
<li>The rejected lines carry 0.74% of the layer’s line optical depth, as a smooth floor of 2–9e−4.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Over the 12-layer path, rejection changes the transmission by up to 0.62% at R = 45,000. tellurix’s optional selection with a 1e−3 budget changes it by at most 4.6e−6, and its default changes nothing.</li>
</ol></li>
</ul>
<p>The floor is smooth, so a fitted continuum absorbs it, which is why the fitted comparisons in Section 4 agree far better than 0.6%.</p>
</section>
<section id="layering-and-continuum" class="level3">
<h3 class="anchored" data-anchor-id="layering-and-continuum">2.7 Layering and continuum</h3>
<p><em>In plain terms.</em> A layer is described by one pressure and one temperature, yet the real air inside it spans a range of both. Which single values best represent the layer? The standard answer, the Curtis–Godson approximation, averages pressure and temperature weighted by the amount of air, and adds up (integrates) each gas’s molecules exactly. Done carelessly, for example by taking the values at the layer’s mid-point, the water column can be wrong by tens of percent in a single layer, because water falls off steeply with height. The continuum (Section 2.3) is evaluated per layer as well.</p>
<p>Both codes average each layer the same way: density-weighted pressure and temperature, and gas amounts integrated with exponential interpolation between levels. They differ in where they put the boundaries. Given the same levels, they agree on the water column to 0.001%.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>LBLRTM 12.17</th>
<th>tellurix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Layer boundaries</td>
<td>AUTLAY (<code>lblatm.f90:5774</code>): a new layer when the Voigt-width ratio reaches 1.5 or the temperature range exceeds 5–8 K; rounded to 0.1 km</td>
<td>fixed count (12 by default) from the ERA5 or AFGL levels (<code>site_profile.py</code>)</td>
</tr>
<tr class="even">
<td>Layer means</td>
<td>ALAYER/FPACK (<code>lblatm.f90:5640–6175</code>): density-weighted P and T, exponentially interpolated densities</td>
<td><code>weighted_layers</code>: the same weighting, written to the profile’s <code>pressure_bar</code> column; centre sampling kept for old records</td>
</tr>
<tr class="odd">
<td>H2O continuum</td>
<td>MT_CKD 4.3 on a 1 cm−1 grid (<code>lblrtm.f90:6215</code>), then interpolated onto the line grid by XINT (<code>oprop.f90:519</code>)</td>
<td>the same coefficients and formulas in JAX; P–T factors fixed at construction, so the continuum stays differentiable in water: self ∝ c², foreign ∝ c(1 − cx)</td>
</tr>
</tbody>
</table>
<p><img src="figures/output/fig_method_layering.png" class="img-fluid" style="width:100.0%" alt="layering"></p>
<p><strong>Figure 2.7a. One ERA5 column (DCT 2018-12-21) given to both codes as the same 24 levels.</strong> (a, b) Temperature and water, with each scheme’s boundaries and layer means: LBLRTM’s AUTLAY makes 19 layers, tellurix 12. (c) Each layer’s water column against a fine integral of the same atmosphere. LBLRTM and weighted tellurix are both within 0.001% in total; centre sampling is 1.55% high overall and up to 36% off in single layers. (d) The earlier 6-layer comparison case: given 7 levels, LBLRTM’s exponential interpolation sags below the layer values by up to 23% in the second layer, which is why its water column came out 12.2% lower.</p>
<p><img src="figures/output/fig_method_continuum.png" class="img-fluid" style="width:100.0%" alt="continuum"></p>
<p><strong>Figure 2.7b. MT_CKD 4.3 water continuum, 4000–6500 cm−1, LBLRTM against tellurix on identical layers.</strong> The median relative difference is 0.0013% (self) and 0.0003% (foreign); the 99th percentile is 0.14% and 0.026%, in the weak, noisy wings. LBLRTM was run with the columns scaled ×100 so that its float32 output resolves τ ~ 1e−5. The committed 0.024–0.107% agreement is therefore an upper bound set by that precision. (c) LBLRTM runs at c = 0.5, 1 and 2 follow tellurix’s analytic scaling, which is what makes the continuum differentiable in the water scale.</p>
</section>
<section id="line-coupling" class="level3">
<h3 class="anchored" data-anchor-id="line-coupling">2.8 Line coupling</h3>
<p><em>In plain terms.</em> Treating each line independently assumes that a collision changes only one transition at a time. When lines crowd together at high pressure, as in a CO2 band, collisions also move intensity from one line to its neighbours. The band’s centre then absorbs more than the sum of independent lines, and its edges less. To first order, Rosenkranz (1975) showed that this adds an antisymmetric partner to each line:</p>
<p><span class="math display">\[
\sigma(\nu) \propto S\,\big[\,{\rm Re}\,w(z) + Y p\,{\rm Im}\,w(z)\,\big]
\]</span></p>
<p>Here Re w is the ordinary Voigt shape, Im w its dispersive companion, which is positive on one side of the line and negative on the other, and Y a coupling coefficient that comes with the line list. The effect is small, about 1% of the CO2 optical depth at 2 µm, but it is systematic across a whole band.</p>
<p>Both codes add AER’s first-order (Rosenkranz) dispersion term S·Y·p to the line. Y is interpolated linearly in temperature between 200, 250, 296 and 340 K (<code>oprop.f90:959–1061</code>). They differ in how the term’s shape is computed:</p>
<ul>
<li><strong>LBLRTM</strong> multiplies its tabulated Voigt by x/α_V (CNVFNV 1322–1349; CONVF4 3943–4003). This is exact for a Lorentz line, but it understates the far-wing dispersion by α_L/α_V (0.63 at 50 hPa).</li>
<li><strong>tellurix</strong> uses the exact Im w(z) with a custom JVP. Differentiating Algorithm 916’s series directly would store every term.</li>
</ul>
<p><img src="figures/output/fig_method_coupling.png" class="img-fluid" style="width:100.0%" alt="coupling"></p>
<p><strong>Figure 2.8. Three coupled CO2 lines near 4998 cm−1 (Yp ≈ −0.007).</strong></p>
<ul>
<li>(a, b) At 800 hPa the two dispersion terms agree to 0.56% of their peak.</li>
<li><ol start="3" type="a">
<li>In the far wing tellurix’s term is 15% larger, because it subtracts a plain Lorentz pedestal where LBLRTM subtracts its CO2 form (2 − x²/B²)L(B). Applying LBLRTM’s form closes the gap to 0.6%. This one difference explains LBLRTM’s 0.90% against tellurix’s 1.04% coupling effect.</li>
</ol></li>
<li><ol start="4" type="a">
<li>At 50 hPa, where Doppler broadening matters, LBLRTM’s term is exactly Voigt × x/α_V, and the exact Im w is broader.</li>
</ol></li>
</ul>
</section>
<section id="instrument-model" class="level3">
<h3 class="anchored" data-anchor-id="instrument-model">2.9 Instrument model</h3>
<p><em>In plain terms.</em> Convolving with the LSF means replacing every sample by a weighted average of its neighbours, with the LSF as the weights. This can be done directly, as a weighted sum over a kernel of finite length, or with the Fourier transform, where convolution becomes a multiplication. Direct summation is fine for a Gaussian, which falls to zero within a few widths. The FTS sinc does not fall to zero: its side lobes decay only as 1/distance. Any kernel cut at a finite length therefore drops part of the response. The FFT treats the whole spectrum at once and avoids the cut.</p>
<p>LBLRTM stops at a scanned spectrum. tellurix carries the model through to detector pixels inside the differentiated function, which is what lets the velocity, LSF width and continuum be fitted with the columns.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>LBLRTM post-processor</th>
<th>tellurix <code>TelluricModel.predict</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Line-spread function</td>
<td>SCANFN kernels in direct space (<code>postsub.f90:80–108</code>): rectangle, triangle, Gauss (±4 HWHM), sinc², sinc (±119 HWHM, 72 zeros); FFTSCN with apodizations and MOPD input (<code>fftscn.f90:110–160</code>)</td>
<td>Gaussian by direct convolution on the constant-velocity grid; unapodized FTS sinc by FFT with the MOPD measured from the spectrum</td>
</tr>
<tr class="even">
<td>Wavelength</td>
<td>none (output on the line grid; INTRPL four-point interpolation, <code>postsub.f90:2527</code>)</td>
<td>velocity shift and stretch, both fitted</td>
</tr>
<tr class="odd">
<td>Detector sampling</td>
<td>none found in the routines read</td>
<td>Simpson integration over each pixel, or point sampling for FTS data</td>
</tr>
<tr class="even">
<td>Continuum</td>
<td>none</td>
<td>Chebyshev log-continuum, fitted</td>
</tr>
</tbody>
</table>
<p><img src="figures/output/fig_method_instrument.png" class="img-fluid" style="width:100.0%" alt="instrument"></p>
<p><strong>Figure 2.9. The instrument model step by step, 4290–4300 cm−1 on IGRINS K pixels 145–460.</strong> (a) Monochromatic transmission on the 0.42 km/s grid. (b) Gaussian LSF, σ = 2.83 km/s. (c) Simpson pixel averages against point samples, which differ by up to 4.6e−3 (rms 7e−4). (d) A +2 km/s shift times the log-Chebyshev continuum. (e) Gaussian and unapodized sinc kernels at equal FWHM. (f) The error of a truncated sinc kernel falls only about as 1/N and is still 3.4e−3 at LBLRTM’s 72-zero extent, which is why tellurix applies the sinc by FFT.</p>
</section>
<section id="numerics-that-make-it-fast-and-differentiable" class="level3">
<h3 class="anchored" data-anchor-id="numerics-that-make-it-fast-and-differentiable">2.10 Numerics that make it fast and differentiable</h3>
<p><em>In plain terms.</em> The previous sections fixed the physics; this one covers four implementation choices that make it fast enough to fit, without changing the answer beyond stated tolerances:</p>
<ol type="1">
<li><strong>Sparse core:</strong> use the expensive Voigt formula only for the 0.1% of line–sample pairs close enough to need it.</li>
<li><strong>Precomputed opacity:</strong> a fit changes the line opacity only weakly, so compute it once and update it with a first-order (Taylor) correction.</li>
<li><strong>Mixed precision:</strong> do the bulk of the arithmetic in 32-bit floating point, after rewriting one formula that would otherwise lose all its accuracy.</li>
<li><strong>Exact gradients:</strong> let autodiff differentiate the whole chain, and show why that beats finite differences.</li>
</ol>
<p>Four techniques carry the speed, and none of them changes the physics. Each is checked against the exact calculation below.</p>
<p><img src="figures/diagrams/gradient_flow.png" class="img-fluid" style="width:100.0%" alt="gradient data flow · from model.py and fit.py"></p>
<p>The column scales reach the optical depth through three routes: linearly, through the self-broadening partial pressure, and through MT_CKD. Everything above the optical depth is fixed once the opacity is precomputed. Velocity, LSF width and continuum act only on the stored spectrum, so they never touch the line kernel.</p>
<p><img src="figures/output/fig_method_sparse_core.png" class="img-fluid" style="width:100.0%" alt="sparse core"></p>
<p><strong>Figure 2.10a. Sparse core.</strong> (a) Of 4,669 H2O lines × 5,348 samples at 5000–5100 cm−1, only 30,130 pairs (0.121%) can reach Algorithm 916 (x² + a² &lt; 111). (b) Which branch each pair takes in the bottom layer. (c) Under vectorization ExoJAX’s Direct evaluates both branches everywhere, and Algorithm 916 on all pairs costs 1018 of its 1270 ms. SparseCoreDirect evaluates it on the core list only, found by <code>searchsorted</code>: 124 ms (10×), agreeing to 2.6e−16, and 7.9 ms (160×) with float32 wings. (d) Recomputing offsets inside the kernel removes 426 MB of (line, grid) matrices, leaving 1.9 MB.</p>
<p><img src="figures/output/fig_method_precompute.png" class="img-fluid" style="width:100.0%" alt="precompute"></p>
<p><strong>Figure 2.10b. Precomputed, linearized opacity.</strong> (a) Transmission error against the H2O scale (0.5–2.7). The first-order expansion in P_self stays below 3.1e−4, against 5.5e−3 photon noise; frozen opacity exceeds the noise at s ≳ 2. (b) The strongest H2O line in the bottom layer: frozen opacity misses its peak by 4% at s = 2.7, linearized opacity by 0.1%. (c) Self-broadening is only about ±2% of dτ/d ln s; the rest is the linear τ = σN term.</p>
<p><img src="figures/output/fig_method_mixed_precision.png" class="img-fluid" style="width:100.0%" alt="mixed precision"></p>
<p><strong>Figure 2.10c. Mixed-precision wings.</strong> Relative error of H, ∂H/∂x and ∂H/∂a in the asymptotic wing, against an extended-precision reference. ExoJAX’s derivative identity (∂H/∂a = 2xL + 2aH − 2/√π) cancels catastrophically in float32, with error growing as x²ε: 15% at x = 1000. tellurix substitutes the truncated series into w′ = −2zw + 2i/√π, which with u = 1/z² gives ∂H/∂x = Im(u + 1.5u² + 3.75u³)/√π. That leaves nothing to cancel, and the error stays at float32 ε (about 1e−7). (d) About 89% of real wing pairs lie at x &gt; 1000.</p>
<p><img src="figures/output/fig_method_gradients.png" class="img-fluid" style="width:100.0%" alt="gradients"></p>
<p><strong>Figure 2.10d. Autodiff against finite differences</strong> of the fitting objective, for the H2O column, velocity and LSF width. Finite differences show the usual V: truncation error falls with the step and round-off grows as ε|f|/h. The best central difference agrees with autodiff to 7e−12 (H2O) and 8e−12 (LSF), but only 1.6e−8 for velocity, because a velocity step enters as λ(1 + v/c) and is lost below εc. On the live float32 kernel the H2O difference stalls at 0.5%: small P_self steps fall below float32 resolution. Autodiff needs no step to be chosen.</p>
<p><strong>Why <code>precompute_opacity</code> itself uses a central difference.</strong> The sparse kernel sits inside a <code>lax.cond</code> that falls back to full Direct outside its temperature and pressure range. Under <code>vmap</code> over layers, the batched predicate turns <code>cond</code> into <code>select</code>, so a JVP would also run the dense fallback. Two extra forward evaluations at ±25% of P_self avoid that.</p>
</section>
</section>
<section id="fitting-and-computational-cost" class="level2">
<h2 class="anchored" data-anchor-id="fitting-and-computational-cost">3. Fitting and computational cost</h2>
<p>A three-stage fit takes 3.3 s on one GPU instead of 61 s. The gain comes from compiling once and taking the line-by-line kernel out of the optimizer loop; making each evaluation faster contributes less (<code>docs/precomputed_opacity_results.json</code>).</p>
<section id="the-fitter" class="level3">
<h3 class="anchored" data-anchor-id="the-fitter">3.1 The fitter</h3>
<ul>
<li>Bounded MAP by L-BFGS-B over <code>jax.value_and_grad</code> (<code>fit_order</code>). Fixed dimensions are removed, free ones rescaled to physical steps, and a convergence with a large projected gradient is rejected. That hardening fixed a 10.88σ LSF-width discrepancy found in validation (<code>docs/mixed_precision_validation.md</code>).</li>
<li>Staged fits: continuum, then velocity, then columns, all sharing one compiled <code>OrderObjective</code>.</li>
</ul>
</section>
<section id="where-the-time-goes" class="level3">
<h3 class="anchored" data-anchor-id="where-the-time-goes">3.2 Where the time goes</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Configuration (synthetic Arcturus-like page, RTX 5000 Ada)</th>
<th style="text-align: right;">Wall clock</th>
<th style="text-align: right;">Speedup</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Compile per stage</td>
<td style="text-align: right;">61.2 s</td>
<td style="text-align: right;">1.0×</td>
</tr>
<tr class="even">
<td>One shared compilation</td>
<td style="text-align: right;">35.4 s</td>
<td style="text-align: right;">1.7×</td>
</tr>
<tr class="odd">
<td>Precomputed opacity + shared compilation</td>
<td style="text-align: right;">3.3 s</td>
<td style="text-align: right;">18.4×</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Precomputed opacity.</strong> A fitted parameter reaches the kernel only through the H2O self-broadening partial pressure, so the opacity is expanded to first order in it and frozen. The maximum transmission error is 6.7e−4 (rms 2.9e−5) over water columns 0.50–2.72× the reference, against 5.5e−3 photon noise. End to end, including the 4.2 s precompute, the fit is 8.1× faster; parameters agree to 1.8e−5.</li>
<li><strong>Sparse core and no dense offset matrix.</strong> The forward model is 7.0× faster and value-plus-gradient 10.4× faster than ExoJAX Direct, agreeing to 3.3e−16. Device memory falls from 426 MB to 1.8 MB.</li>
<li><strong>Mixed precision.</strong> A further 11.1× forward and 8.0× gradient speedup on a 2048-pixel H2O order; it passes 588-state opacity, Jacobian and paired-fit checks (worst parameter shift 1.09e−4 σ).</li>
<li><strong>Grid margin ≠ line margin.</strong> Lines are selected 25 cm−1 wide, but the grid is trimmed to 5 cm−1: 3.3× fewer points atlas-wide, at a maximum flux difference of 2.5e−4.</li>
<li>A real Arcturus page now costs about 13 s, against about 57 s before. The 598 page-epochs take about 45 min on three GPUs (<code>docs/arcturus_batch_timing.json</code>).</li>
</ul>
<p>For context, one LBLRTM 12.17 run over the same 20 cm−1 interval takes 266 ms. The warmed GPU forward model was about 2.4× faster even before these changes, and it also returns gradients.</p>
</section>
<section id="against-lblrtm-stage-by-stage" class="level3">
<h3 class="anchored" data-anchor-id="against-lblrtm-stage-by-stage">3.3 Against LBLRTM, stage by stage</h3>
<p>On one GPU, tellurix beats LBLRTM at every warm stage. The biggest gain is the gradient: with precomputed opacity, a gradient costs 3.6–4.4 ms against 1.05 s for LBLRTM finite differences (237–294× on K92). A cold fit still loses: an LBLRTM-in-the-loop fit converges in about 21 runs (5 s), while tellurix spends about 8 s compiling. tellurix wins once the compilation is reused across orders or frames. Source: <code>docs/lblrtm_tellurix_performance.json</code>, <code>benchmarks/benchmark_lblrtm_stages.py</code>.</p>
<p><strong>Setup.</strong> Both codes use identical 12-layer ERA5 layers, AER 3.9 H2O and CO2 lines, MT_CKD and pressure shifts, a 30° zenith angle, and no line coupling. LBLRTM runs on one CPU core; tellurix runs on one RTX 5000 Ada GPU and, for comparison, on 64 CPU threads. Windows are W1 = 5000–5020 cm−1, W2 = 5000–5100 cm−1 and W3 = IGRINS K92 (2048 px, 13,317 lines). Warm times are medians of at least 10 calls.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Stage, W3 (K92)</th>
<th style="text-align: right;">LBLRTM</th>
<th style="text-align: right;">tellurix GPU</th>
<th style="text-align: right;">tellurix CPU</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Line preparation (LNFL; AER read + core lists)</td>
<td style="text-align: right;">12.3 s</td>
<td style="text-align: right;">0.95 s (13×)</td>
<td style="text-align: right;">1.4 s (9×)</td>
</tr>
<tr class="even">
<td>Line-by-line optical depth</td>
<td style="text-align: right;">103 ms</td>
<td style="text-align: right;">13.4 ms (7.7×)</td>
<td style="text-align: right;">900 ms (0.11×)</td>
</tr>
<tr class="odd">
<td>Continuum, layers, slant path</td>
<td style="text-align: right;">28 ms</td>
<td style="text-align: right;">0.15 ms</td>
<td style="text-align: right;">0.62 ms</td>
</tr>
<tr class="even">
<td>Instrument: LSF, pixels, continuum</td>
<td style="text-align: right;">15 ms</td>
<td style="text-align: right;">1.4 ms</td>
<td style="text-align: right;">1.2 ms</td>
</tr>
<tr class="odd">
<td>Forward model</td>
<td style="text-align: right;">167 ms</td>
<td style="text-align: right;">13.4 ms (12×)</td>
<td style="text-align: right;">970 ms (0.17×)</td>
</tr>
<tr class="even">
<td>Forward, precomputed opacity</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1.3 ms</td>
<td style="text-align: right;">1.4 ms</td>
</tr>
<tr class="odd">
<td>Gradient: central FD (5 runs) against autodiff</td>
<td style="text-align: right;">1.05 s</td>
<td style="text-align: right;">29 ms (36×)</td>
<td style="text-align: right;">1.22 s (0.86×)</td>
</tr>
<tr class="even">
<td>Gradient, precomputed opacity</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4.4 ms (237×)</td>
<td style="text-align: right;">3.6 ms (294×)</td>
</tr>
<tr class="odd">
<td>Full fit, cold (first call, compilation included)</td>
<td style="text-align: right;">5.1 s</td>
<td style="text-align: right;">25.5 s</td>
<td style="text-align: right;">17.6 s</td>
</tr>
<tr class="even">
<td>Full fit, compiled objective reused</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.1 s</td>
<td style="text-align: right;">6.7 s</td>
</tr>
</tbody>
</table>
<p>The LBLRTM fit column counts the runs (21) its least-squares fit needed.</p>
<p><img src="figures/output/fig_performance_stages.png" class="img-fluid" style="width:100.0%" alt="stage by stage"></p>
<p><strong>Figure 3a. Stage by stage, three windows.</strong> Whiskers mark the first call, including XLA compilation. The live-opacity forward model on CPU is the one stage where LBLRTM wins.</p>
<p><strong>Which stage gains most from JAX:</strong></p>
<ol type="1">
<li><strong>Gradients (150–330× with precomputed opacity).</strong> The fitted columns enter linearly, so the kernel runs once and each gradient takes milliseconds on either device. This comes from reformulating the model for autodiff, not from GPU arithmetic.</li>
<li><strong>The line-by-line kernel on GPU (5–13×).</strong> It is pure arithmetic over line–sample pairs. On CPU tellurix is 5–15× slower than LBLRTM, which evaluates far wings on a coarse grid and rejects about 90% of near lines per layer, while tellurix evaluates every line in full Voigt.</li>
<li><strong>Continuum, layer merge and instrument (10–190×).</strong> These are small in absolute terms, under 30 ms in LBLRTM.</li>
<li><strong>Line preparation (9–13×)</strong> against LNFL. It is one-time in both codes.</li>
</ol>
<p><img src="figures/output/fig_performance_scaling.png" class="img-fluid" style="width:100.0%" alt="scaling"></p>
<p><strong>Figure 3b. Scaling with window width.</strong> LBLRTM’s run time grows slowly with width; tellurix’s live opacity grows with the line count, while precomputed opacity stays flat at 1–4 ms.</p>
<p><strong>Autodiff.</strong></p>
<ul>
<li><strong>Cost.</strong> A gradient costs 1.8–2.2× a forward run with live opacity, and 3–4× with precomputed opacity. The cost is flat from 1 to 16 free parameters. LBLRTM needs P + 1 or 2P + 1 runs, though only column scales need reruns; velocity, LSF and continuum act on the stored spectrum.</li>
<li><strong>Accuracy.</strong> Autodiff matches tellurix’s own central difference to 1e−5 rms (2e−4 at worst on the χ2 gradient). Against LBLRTM’s finite-difference Jacobian it agrees to 1.8–3.4% rms (correlation ≥ 0.999), which is the size of the flux difference between the two codes.</li>
<li><strong>Full Jacobian</strong> (<code>jacfwd</code>, 16 parameters): 2–3 ms with precomputed opacity, and 48–260 ms live on GPU.</li>
</ul>
<p><img src="figures/output/fig_performance_gradient.png" class="img-fluid" style="width:100.0%" alt="gradient vs parameters"></p>
<p><strong>Figure 3c. Gradient cost against the number of free parameters, K92.</strong> LBLRTM finite differences grow linearly; tellurix reverse-mode autodiff is flat. Open squares and diamonds are measured LBLRTM finite differences.</p>
<p><img src="figures/output/fig_performance_fit.png" class="img-fluid" style="width:100.0%" alt="end to end fit"></p>
<p><strong>Figure 3d. End-to-end fit to S/N 200 synthetic spectra, and the columns it recovers.</strong> An LBLRTM-in-the-loop fit (scipy <code>least_squares</code> with finite differences) converges in 20–23 runs and 3.6–5.9 s. A cold tellurix fit takes 22–26 s on GPU, of which about 8 s is compilation; reusing the compiled objective brings it to 0.65–5.1 s. Both recover the columns to within 1%.</p>
<p><strong>Caveats.</strong></p>
<ul>
<li>LBLRTM uses its own monochromatic grid (0.0014–0.0078 cm−1) with line rejection and a 25 cm−1 cutoff, and writes single-precision output. tellurix uses a 0.028 cm−1 grid with full Voigt lines.</li>
<li>LBLRTM includes all its continua; tellurix only MT_CKD H2O.</li>
<li>The machine was shared (load average 1–12), and the tellurix CPU row used all 64 threads.</li>
<li>Float64 wings are 7–15× slower on GPU, and the float64 W2 gradient ran out of the 32 GB of GPU memory, so the GPU rows use mixed precision.</li>
</ul>
</section>
<section id="uncertainties" class="level3">
<h3 class="anchored" data-anchor-id="uncertainties">3.4 Uncertainties</h3>
<ul>
<li><code>FitResult.covariance</code> inverts the actual Hessian of the free, unbounded parameters. It is a formal error that assumes independent pixels.</li>
<li>The residual is dominated by correlated stellar error, so formal errors are 3–9× too small. For the water column, the formal error is 0.76% while sub-window scatter is 6.5–9%. The paper quotes empirical scatter and uses <code>FitResult.correlation</code> only for degeneracies.</li>
</ul>
</section>
</section>
<section id="validation-against-lblrtm" class="level2">
<h2 class="anchored" data-anchor-id="validation-against-lblrtm">4. Validation against LBLRTM</h2>
<p>Given the same layers, tellurix matches LBLRTM 12.17 to 0.010% median and 0.039% at the 99th percentile at R = 45,000 after a fit, with line coupling on. The section’s message is that agreement with LBLRTM tests the implementation, not the physics; the observations judge the physics (Sections 5–7).</p>
<p>Acceptance thresholds, for pixels with reference transmission &gt; 0.05: median |ΔT| &lt; 1e−3, 99th percentile &lt; 5e−3, line displacement &lt; 0.1 resolution element.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Window (cm−1)</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">99th pct.</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CO only, no continuum, R = 45,000</td>
<td>4290–4310</td>
<td style="text-align: right;">4.6e−5</td>
<td style="text-align: right;">2.2e−3</td>
<td><code>aer_co_validation.json</code></td>
</tr>
<tr class="even">
<td>MT_CKD 4.3 water continuum, 3 P–T–H2O states (relative τ)</td>
<td>5000–5020</td>
<td style="text-align: right;">0.024–0.076%</td>
<td style="text-align: right;">≤ 0.107% (limited by LBLRTM’s float32 output; see 2.7)</td>
<td><code>native_mt_ckd_validation.json</code></td>
</tr>
<tr class="odd">
<td>Full atmosphere, identical layers, columns + linear continuum fitted</td>
<td>5000–5020</td>
<td style="text-align: right;">0.047%</td>
<td style="text-align: right;">0.69%</td>
<td><code>lblrtm_identical_layers.json</code></td>
</tr>
<tr class="even">
<td>Same, with first-order CO2 line coupling</td>
<td>5000–5020</td>
<td style="text-align: right;">0.010%</td>
<td style="text-align: right;">0.039%</td>
<td><code>lblrtm_identical_layers.json</code></td>
</tr>
<tr class="odd">
<td>Same with coupling, K orders K86 / K89 / K92</td>
<td>IGRINS K</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.032 / 0.146 / 0.25%</td>
<td><code>lblrtm_identical_layers_k_orders.json</code></td>
</tr>
<tr class="even">
<td>Layering: 12 weighted layers vs a 150-layer reference, fitted</td>
<td>4 IGRINS windows</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.04–0.06%</td>
<td><code>layering_comparison.json</code></td>
</tr>
</tbody>
</table>
<p>The CO-only line displacement is 0.015 resolution element.</p>
<p>Points to make in the text:</p>
<ul>
<li><strong>The apparent 5.8% gap was the harness, not the physics.</strong> Handed 7 levels, LBLRTM re-layers them into 13 layers (18 integration sub-layers) and interpolates water exponentially between levels, giving 12.2% less water column (2.143e22 against 2.440e22 cm−2). Passing tellurix’s own layers (IATM = 0) removes it. Fitted scales then come out at 1.001 for H2O and 1.000 for CO2.</li>
<li><strong>CO2 line coupling is the remaining physics difference.</strong> LBLRTM applies AER first-order coupling to 5,679 of 11,849 CO2 lines near this window. Coupling lowers the window’s CO2 optical depth by 0.90% in LBLRTM and by 1.04% in tellurix. The 25 cm−1 cutoff and pedestal carry 0.7% of CO2, but at 5000–5020 cm−1 the fitted continuum absorbs them. Not in K92: there the cutoff in far water-line wings leaves 0.25% at the 99th percentile, falling to 0.055% when tellurix also applies the cutoff (`lblrtm_identical_layers_k_orders.json`).</li>
<li><strong>The continuum residual is not identified.</strong> LBLRTM’s continua average τ = 0.0066 against MT_CKD water’s 0.0028; the difference is smooth and absorbed by the fitted continuum.</li>
<li><strong>The offline correction template</strong> (<code>lblrtm_corrected</code>) brings the 99th percentile to 4.75e−5 for its fixed profile, and stays below 2.34e−3 at 0.5–2× water and air mass 1–2.5. Present it briefly, as a consistency demonstration.</li>
<li><strong>Gradients and recovery.</strong> Mixed-precision checks: 588 molecular states, 45 spectra, Jacobian columns, and paired fits on 3 noise seeds (table in Section 3).</li>
</ul>
<section id="figures" class="level3">
<h3 class="anchored" data-anchor-id="figures">4.1 Figures</h3>
<p>All numbers below are recomputed by <code>paper/figures/fig_lblrtm_comparison.py</code> from the saved LBLRTM TAPE12s and agree with the committed JSON reports to every printed digit.</p>
<p><img src="figures/output/fig_lblrtm_5000.png" class="img-fluid" style="width:100.0%" alt="tellurix vs LBLRTM 5000-5020"></p>
<p><strong>Figure 4a. tellurix against LBLRTM 12.17 at 5000–5020 cm−1, identical layers.</strong> Shown at R = 45,000 after fitting H2O and CO2 scales and a linear continuum. Without line coupling the residual is a CO2 band pattern of ±0.7% (median 0.047%, 99th percentile 0.69%). With first-order coupling it is flat at 0.010% / 0.039%. Gaps are saturated cores (T ≤ 0.05), excluded by the metric.</p>
<p><img src="figures/output/fig_lblrtm_5000_zoom.png" class="img-fluid" style="width:100.0%" alt="zoom on worst residual"></p>
<p><strong>Figure 4b. Zoom on the worst residual without coupling</strong> (5001.29 cm−1), monochromatic and at R = 45,000. Without coupling the monochromatic difference is an antisymmetric ±0.8% around a saturated CO2 line, the signature of line mixing. With coupling it is about ±0.03%, so the agreement holds line by line, not only after convolution.</p>
<p><img src="figures/output/fig_lblrtm_K92.png" class="img-fluid" style="width:100.0%" alt="K92 order"></p>
<p><strong>Figure 4c. The worst K order, K92 (5122–5193 cm−1).</strong> Coupling lowers the 99th percentile only from 0.43% to 0.25%. All three K orders (median / 99th percentile):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Order</th>
<th>No coupling</th>
<th>With coupling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>K86</td>
<td>0.077% / 0.52%</td>
<td>0.0072% / 0.032%</td>
</tr>
<tr class="even">
<td>K89</td>
<td>0.27% / 1.28%</td>
<td>0.034% / 0.146%</td>
</tr>
<tr class="odd">
<td>K92</td>
<td>0.071% / 0.43%</td>
<td>0.058% / 0.25%</td>
</tr>
</tbody>
</table>
<p><img src="figures/output/fig_lblrtm_K92_zoom.png" class="img-fluid" style="width:100.0%" alt="K92 zoom"></p>
<p><strong>Figure 4d. K92 zoom at its worst residual</strong> (5182.11 cm−1). tellurix absorbs about 0.25% more across a broad, smooth stretch between strong water lines, and the coupled and uncoupled curves coincide there. This is LBLRTM’s 25 cm−1 line cutoff acting on far water wings, not coupling.</p>
<p><img src="figures/output/fig_lblrtm_co.png" class="img-fluid" style="width:100.0%" alt="CO only"></p>
<p><strong>Figure 4e. The first rung: CO only, 4290–4310 cm−1, no continuum</strong> (median 0.005%, 99th percentile 0.22%). tellurix’s CO cores are uniformly deeper, by up to 0.27%. This rung used LBLRTM’s own re-layered atmosphere, no pressure shifts and plain Direct opacity, so it is not like-for-like with Figures 4a–d.&nbsp;It belongs as a historical rung, or should be rerun with identical layers.</p>
</section>
</section>
<section id="application-to-fts-atlases" class="level2">
<h2 class="anchored" data-anchor-id="application-to-fts-atlases">5. Application to FTS atlases</h2>
<p>The FTS atlases test the line physics at 4–10× IGRINS resolution and very high S/N. There, the stellar model, not the telluric model, sets the residual floor. tellurix corrects the whole Arcturus IR atlas (598 page-epochs, 0.91–5.36 µm) and four NSO Kitt Peak solar data sets.</p>
<section id="instrument-profile-measured-from-the-spectrum" class="level3">
<h3 class="anchored" data-anchor-id="instrument-profile-measured-from-the-spectrum">5.1 Instrument profile measured from the spectrum</h3>
<ul>
<li>Every atlas is fitted with an unapodized sinc ILS applied by FFT. Each page’s MOPD is measured from its own interferogram envelope (<code>ils.py</code>).</li>
<li><strong>Arcturus:</strong> five sampling bands, MOPD 25.3–25.6 cm at 0.010 cm−1 down to 6.74 cm at 0.040 cm−1. The two epochs differ by 11.5% in R at 2 µm (126,000 against 113,000).</li>
<li><strong>Solar:</strong> FWHM 0.01753 cm−1 for photatl and the 1990 pair, 0.01859 for niratl, 0.041–0.042 for the 1983 pair. The ftsspec headers misstate resolution by up to 3.02×, and Wallace 2011’s measured R is 577,000/441,000 rather than the stated 676,000/698,000.</li>
<li>A Gaussian ILS in place of the sinc raises the rms 1.24× and biases CO2 by +0.61% (synthetic test, <code>arcturus_validation.json</code>).</li>
</ul>
</section>
<section id="arcturus-hinkle-wallace-livingston-1995" class="level3">
<h3 class="anchored" data-anchor-id="arcturus-hinkle-wallace-livingston-1995">5.2 Arcturus (Hinkle, Wallace &amp; Livingston 1995)</h3>
<ul>
<li><strong>Source:</strong> a fixed Payne Zero synthesis (T_eff 4286 K, log g 1.66, [M/H] −0.52, [α/M] 0.30). Converging its atmosphere changes residuals by only about 0.5%, so the stellar error is in the line list.</li>
<li><strong>Atlas-wide:</strong> 822,928 pixels fitted, median residual 4.48σ; 19.4% of fits have a parameter at a bound.</li>
<li><strong>Error budget at 2 µm (ab5000):</strong> rms 0.0221 against photon noise 0.0055, telluric about 0.009, stellar about 0.012.</li>
<li><strong>Two-epoch test</strong> (<code>arcturus_two_epoch.json</code>). The fitted stellar velocity separation is 40.427 km/s against 40.44 from the atlas. Residuals correlate at r = 0.824 in the stellar frame and r = 0.152 in the telluric frame, so what remains is stellar. The model-ratio correction halves the epoch difference (0.0357 to 0.0183).</li>
<li><strong>Against the atlas’s own telluric spectrum:</strong> H2O agrees to −0.3% on ab5000, but CO2 differs by −10.3%. Atlas-wide, the published telluric spectrum carries 8–10% less absorption (k = 0.901 summer, 0.918 winter). It came from separate McMath lunar observations, so agreement with it is only a consistency check.</li>
<li><strong>Caveat:</strong> the atlas gives no air mass, so fitted column scales include it and cannot be compared between pages. Only ratios of species on one page are free of air mass.</li>
</ul>
</section>
<section id="nso-kitt-peak-solar-atlases" class="level3">
<h3 class="anchored" data-anchor-id="nso-kitt-peak-solar-atlases">5.3 NSO Kitt Peak solar atlases</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Data set</th>
<th>Coverage (cm−1)</th>
<th>Air mass</th>
<th style="text-align: right;">Windows</th>
<th style="text-align: right;">Residual rms</th>
<th style="text-align: right;">Solar-line rms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ftsspec 1990-12-18, file 5 (= photatl, rescaled)</td>
<td>1876–9091</td>
<td>1.985</td>
<td style="text-align: right;">224 × 30 cm−1</td>
<td style="text-align: right;">1.03%</td>
<td style="text-align: right;">4.69%</td>
</tr>
<tr class="even">
<td>ftsspec 1990-12-18, file 4</td>
<td>1876–9091</td>
<td>4.73</td>
<td style="text-align: right;">224</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>niratl</td>
<td>8900–13600</td>
<td>1.10 (from the O2 A band)</td>
<td style="text-align: right;">188 pages</td>
<td style="text-align: right;">1.20%</td>
<td style="text-align: right;">3.82%</td>
</tr>
<tr class="even">
<td>ftsspec 1983-06-26, files 2 and 3</td>
<td>8516–20735</td>
<td>5.37, 3.09</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1.67%, 1.62%</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Source:</strong> Payne Zero (5772 K, log g 4.438, solar metallicity) as disc-integrated flux, fitted with v sin i = 0 to the disc-centre atlases.</li>
<li><strong>The ~1% floor is the stellar model.</strong> The flux/intensity mismatch is 28.5% of the line-floor variance. The Wallace 2011 and IAG residuals correlate at r = 0.996, so the rest belongs to Payne Zero (<code>solar_floor_split.json</code>). This was measured at 0.74–0.93 µm only.</li>
<li><strong>Air-mass fold.</strong> Folding file 4 onto file 5 is exact for CO and CO2 (≤ 0.01%), and water is low by 0.40–1.18% (saturation). Files 4 and 5 still disagree by about 4%, attributed to the scan-averaged air mass.</li>
<li><strong>Minor species.</strong> Adding OCS and O3 takes the 2030–2060 cm−1 window from 3.75× to 1.47× noise.</li>
<li><strong>O2.</strong> The O2 collision-induced continuum, ported from LBLRTM, agrees with it to 0.13%. It changes the corrected spectra by up to 9.3% at 1.27 µm. The 1983 file pair shows a B/A excess of 1.024–1.027 that two independent atlases do not: IAG 2014 gives 0.980 ± 0.009, Kitt Peak 1989 gives 0.976 ± 0.013, and the lab value is 0.969. AER against HITRAN, line coupling, temperature and line width are each ruled out at under 1%. The paper reports the excess as a property of that file pair.</li>
</ul>
</section>
<section id="figures-1" class="level3">
<h3 class="anchored" data-anchor-id="figures-1">5.4 Figures</h3>
<p>In every typical and bad case below, the largest residuals sit on stellar lines that Payne Zero draws wrong, not on telluric lines. Pages and windows are chosen by a rule written in each script (<code>paper/figures/fig_arcturus_pages.py</code>, <code>fig_solar_pages.py</code>). Solar windows are ranked by the telluric residual: the rms of (observed − model)/continuum over pixels with T_eff &lt; 0.9. Residual/noise is not used for them, because solar noise varies about 100× between windows and that ranking would only order them by S/N.</p>
<p><img src="figures/output/fig_arcturus_typical.png" class="img-fluid" style="width:100.0%" alt="Arcturus typical page"></p>
<p><strong>Figure 5a. A typical Arcturus page, 2.05 µm CO2</strong> (ab4850 winter). Its residual is 4.52σ, the 51st percentile of the atlas. Rows: data and model, effective transmission, corrected spectrum against Payne Zero, residual/σ; right, a 5 cm−1 zoom. The residual is 15.0σ rms where Payne Zero has a line deeper than 5% and 3.0σ elsewhere. Payne Zero lacks the 4857.3 cm−1 line and draws 4872 cm−1 too deep.</p>
<p><img src="figures/output/fig_arcturus_good_bad.png" class="img-fluid" style="width:100.0%" alt="Arcturus good and bad"></p>
<p><strong>Figure 5b. Good and bad Arcturus pages</strong> (10th and 90th percentiles of telluric-rich pages).</p>
<ul>
<li><strong>Good:</strong> ab8650 summer, 1.15 µm water, 2.52σ. The residual is near noise at every depth, yet the corrected spectrum scatters by up to 10% in water-line wings, because the noise is divided by T ≈ 0.5.</li>
<li><strong>Bad:</strong> ab1993 winter, 5.0 µm, 8.11σ. T_eff is a featureless 0.7–0.8, yet residuals reach ±25σ on every stellar line. Our corrected spectrum agrees with the atlas’s own telluric-divided spectrum to rms 0.031, and both differ from Payne Zero by 0.078. The failure is the stellar model.</li>
</ul>
<p><img src="figures/output/fig_arcturus_atlas_telluric.png" class="img-fluid" style="width:100.0%" alt="Arcturus vs atlas telluric"></p>
<p><strong>Figure 5c. Our transmission against the atlas’s published telluric spectrum.</strong> On ab4850 the median |difference| is 0.0069 and k = 0.98. The atlas column exceeds 1 in saturated cores, so those points are excluded (grey). Atlas-wide, the median |difference| is 0.0142, and the atlas carries about 9% less optical depth (k = 0.90 summer, 0.92 winter). It comes from a separate lunar observation, so this is a consistency check, not a truth test.</p>
<p><img src="figures/output/fig_solar_photatl_typical.png" class="img-fluid" style="width:100.0%" alt="Solar photatl typical"></p>
<p><strong>Figure 5d. A typical solar window, photatl / file 5, 1996–2026 cm−1</strong> (5.0 µm CO, CO2, H2O, O3). It is the median telluric-rich window, with a telluric residual of 0.93%. The photatl solar column is overlaid. corrected − Payne Zero has rms 1.17%, while photatl solar − Payne Zero has 1.66%. The telluric residual is 1.70% on solar lines and 0.72% off them.</p>
<p><img src="figures/output/fig_solar_niratl_typical.png" class="img-fluid" style="width:100.0%" alt="Solar niratl typical"></p>
<p><strong>Figure 5e. A typical niratl window, 10622–10653 cm−1</strong> (0.94 µm water). Its telluric residual is 1.39%, the 52nd percentile. corrected − Payne Zero has rms 2.05%, against 2.37% for the atlas’s own solar column. The atlas column dips in saturated water wings where ours stays flat, but ours overshoots by about 7% at 10630.2 cm−1.</p>
<p><img src="figures/output/fig_solar_o2_worst.png" class="img-fluid" style="width:100.0%" alt="O2 A band and worst window"></p>
<p><strong>Figure 5f. The O2 A band, and the worst window.</strong></p>
<ul>
<li><strong>A band</strong> (niratl 13097–13128 cm−1): telluric residual 0.86%. The O2 column is nominal (log scale −0.007) and the corrected spectrum is within about 1% of Payne Zero.</li>
<li><strong>Worst of 254 windows</strong> (file 5, 6706–6736 cm−1, 1.49 µm): 3.10%, against a median of 1.15%. A broad solar line near 6719.6 cm−1 (possibly Mg I 1.488 µm, not yet identified) is too shallow in Payne Zero, and it sits under water lines where the atlas’s solar column is interpolated. CO2 is fitted at 4.0× nominal there, probably absorbing that stellar error.</li>
</ul>
</section>
</section>
<section id="application-to-igrins" class="level2">
<h2 class="anchored" data-anchor-id="application-to-igrins">6. Application to IGRINS</h2>
<p>On A0V standards from three sites, tellurix fits every H and K order to about 1.3σ on a dry night. A night calibration from standards then corrects held-out stars and science targets with one water scale and one velocity per frame. The one per-night systematic found came from the header air mass, not from the model: averaging sec z over the exposure sequence takes the three-night χ² from 8.81 to 0.62.</p>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">6.1 Data</h3>
<p>All data are RRISA reduced spectra: H has 28 orders over 1.430–1.835 µm, K has 26 over 1.847–2.519 µm, 2048 px each.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Night</th>
<th>Site</th>
<th style="text-align: right;">Frames</th>
<th>Air mass</th>
<th style="text-align: right;">PWV (mm)</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2021-03-16</td>
<td>Gemini South</td>
<td style="text-align: right;">14</td>
<td>1.27–1.78</td>
<td style="text-align: right;">5.2</td>
<td>ladder (ERA5 only)</td>
</tr>
<tr class="even">
<td>2018-12-20</td>
<td>DCT</td>
<td style="text-align: right;">10 (5 stars)</td>
<td>1.07–2.50</td>
<td style="text-align: right;">~2.4</td>
<td>ladder, transfer, science (6 targets)</td>
</tr>
<tr class="odd">
<td>2018-04-03</td>
<td>Gemini South</td>
<td style="text-align: right;">1 (HIP 53433)</td>
<td>1.04</td>
<td style="text-align: right;">—</td>
<td>single-frame demonstration, H</td>
</tr>
<tr class="even">
<td>2017-04-20</td>
<td>McDonald</td>
<td style="text-align: right;">8 (7 stars)</td>
<td>1.02–2.99</td>
<td style="text-align: right;">~10.7</td>
<td>ladder, transfer</td>
</tr>
<tr class="odd">
<td>2016-12-08</td>
<td>DCT</td>
<td style="text-align: right;">11 (10 stars)</td>
<td>1.06–2.59</td>
<td style="text-align: right;">~6.9</td>
<td>ladder</td>
</tr>
<tr class="even">
<td>2015-12-01, 2015-12-03</td>
<td>McDonald</td>
<td style="text-align: right;">7, 6</td>
<td>—</td>
<td style="text-align: right;">—</td>
<td>residual structure only</td>
</tr>
</tbody>
</table>
</section>
<section id="method" class="level3">
<h3 class="anchored" data-anchor-id="method">6.2 Method</h3>
<ul>
<li><strong>Per-order fit:</strong> per-species columns, velocity, Gaussian LSF width, and a degree-9 log-Chebyshev continuum, with Simpson pixel integration. A fixed order rule decides which pixels count: throughput ≥ 0.25 of the smoothed peak, T ≥ 0.15, ±600 km/s around H lines, and ≥ 256 px per order.</li>
<li><strong>Atmosphere</strong> from ERA5, anchored at the header station pressure; ERA5 pressure matches BARPRESS to 0.2%.</li>
<li><strong>Stellar source:</strong> Payne Zero A0V (9,500 K, log g 4.1, v sin i fixed at 150 km/s) with its own velocity stage. It reduces the Brackett-window residual 6× (13.97σ to 2.33σ) and recovers 41% more H pixels.</li>
<li><strong>Lamp-flat blaze</strong> (<code>flat.py</code>) and a leave-one-out <strong>response pattern</strong>. The pattern belongs to the spectrograph: it correlates across sites at r = 0.89–0.95, and a master pattern captures 74–88% of it.</li>
<li><strong>Night calibration:</strong> median dry columns, LSF and velocity; water linear in time. A science frame fits only one velocity shift and one water scale.</li>
<li><strong>Sequence air mass:</strong> mean sec z over the exposure sequence (<code>igrins_pointing.py --sequence</code>). The header gives the first exposure’s value; for example, k Tau’s 8 exposures span a mean of 3.23 against 2.96 at the first.</li>
</ul>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">6.3 Results</h3>
<ul>
<li><strong>Fit quality.</strong> Ladder residuals with the pattern are 1.30σ (H) and 1.29σ (K) on DCT 2018. The flat blaze brings per-pixel z from 1.43 to 1.15 (H) and 1.58 to 1.41 (K). Line-free pixels on DCT 2018 sit at z = 0.98 (H) and 0.83 (K).</li>
<li><strong>Across nights.</strong> Residuals rise with water: H/K = 1.30/1.32 (DCT 2018), 1.86/1.59 (DCT 2016), 1.76/1.64 (Gemini 2021), 1.76/2.24 (McDonald 2017). The wettest night is about 1.4× worse at every transmission level.</li>
<li><strong>The per-night systematic</strong> (table below, <code>igrins_dry_systematic.json</code>). Predicted and measured dry factors correlate at r = 0.995 (McDonald 2017) and 0.992 (DCT 2016). Frame scatter falls from 0.035/0.025 to 0.004, and the residuals do not change. Line coupling, blaze, fringe, veiling, per-frame atmosphere and non-linearity were all ruled out first.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Air mass used</th>
<th>CO2 slopes per air mass (3 nights)</th>
<th style="text-align: right;">χ² (2 dof), CO2</th>
<th style="text-align: right;">χ², CH4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Header, first exposure</td>
<td>+0.0051, +0.0481, −0.0285</td>
<td style="text-align: right;">8.81</td>
<td style="text-align: right;">7.34</td>
</tr>
<tr class="even">
<td>Exposure-sequence mean</td>
<td>−0.0010, −0.0012, −0.0050</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">1.99</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Transfer to held-out standards</strong> (5 night-bands, 1,282 order-frames). Pure interpolation of the night calibration is 1.2–1.9× noise. Fitting one water scale and one shift per frame brings this to 0.3–0.5× noise in absorbing orders (0.95× for McDonald K). H and K water shifts agree to 0.005–0.006 (r = 0.997/0.998).</li>
<li><strong>Science targets</strong> (DCT 2018). 4 extra standards reach 0.89–1.11σ, and the median H−K water difference across targets is 0.007. GJ 281 is flagged at 0.022.</li>
<li><strong>CO2 line coupling</strong> improves the 2.0 µm band centre: K89 z falls from 1.97 to 1.68 in 10 of 10 frames. It costs 1–3% at the band edges (K86, K92), where tellurix still matches LBLRTM.</li>
<li><strong>Comparison:</strong> the PLP’s MODEL_TELTRANS is off by −0.316 at T = 0.4–0.6 on the demonstration frame.</li>
</ul>
</section>
<section id="known-limitations" class="level3">
<h3 class="anchored" data-anchor-id="known-limitations">6.4 Known limitations</h3>
<p>Known limitations: the Gaussian LSF misses deep cores by about 3σ, v sin i is fixed, the ±600 km/s mask biases absolute columns by a few percent, and O2, CO and N2O are not measurable here.</p>
</section>
<section id="figures-2" class="level3">
<h3 class="anchored" data-anchor-id="figures-2">6.5 Figures</h3>
<p>Each order and frame below was chosen by a rule, not by eye. Orders: those with at least 25% of fitted pixels below T = 0.8 on the dry night, taking the one whose median z_rms is closest to its band’s median, which gives H122 (1.474 µm) and K88 (2.02 µm). z_rms is the rms of (observed − model)/σ over reliable pixels. Scripts are in <code>paper/figures/fig_igrins_*.py</code>.</p>
<p><img src="figures/output/fig_igrins_standard.png" class="img-fluid" style="width:100.0%" alt="IGRINS standard, H122 and K88"></p>
<p><strong>Figure 6a. A median frame on the dry night</strong> (DCT 2018-12-20, frame 0084, HD 53205, air mass 1.45). Rows: observed flux with model, telluric transmission, corrected spectrum against the A0V model, residual/σ, then 200-pixel zooms. H122 has z_rms 1.67 (59th percentile of 268 H order-frames) and K88 has 1.58 (52nd of 246). Residuals reach ±5σ in deep cores, the Gaussian-LSF limitation noted in Section 6.4.</p>
<p><img src="figures/output/fig_igrins_good_bad.png" class="img-fluid" style="width:100.0%" alt="IGRINS good and bad, dry and wet"></p>
<p><strong>Figure 6b. Good and bad, dry and wet.</strong> (a) Cumulative z_rms over every order-frame: dry DCT 2018 has a median of 1.56 (N = 514) and wet McDonald 2017 one of 2.28 (N = 388). (b) K88 z_rms against sequence air mass. (c–f) The best and worst K88 frame of each night over the same 220 pixels:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Panel</th>
<th>Night</th>
<th>Frame</th>
<th style="text-align: right;">Air mass</th>
<th>K88 z_rms (percentile)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(c) best</td>
<td>dry</td>
<td>0090, HR 2893</td>
<td style="text-align: right;">1.30</td>
<td>1.38 (38th)</td>
</tr>
<tr class="even">
<td>(e) worst</td>
<td>dry</td>
<td>0033, χ Cap</td>
<td style="text-align: right;">2.48</td>
<td>2.46 (90th)</td>
</tr>
<tr class="odd">
<td>(d) best</td>
<td>wet</td>
<td>0151, HR 7384</td>
<td style="text-align: right;">1.02</td>
<td>1.85 (28th)</td>
</tr>
<tr class="even">
<td>(f) worst</td>
<td>wet</td>
<td>0074, HR 3651</td>
<td style="text-align: right;">1.93</td>
<td>2.66 (65th)</td>
</tr>
</tbody>
</table>
<p>The worst frames leave line-core residuals of about −5σ. DCT H107 (z = 115) and H104 (z = 33) are excluded and named on the panel.</p>
<p><img src="figures/output/fig_igrins_science.png" class="img-fluid" style="width:100.0%" alt="IGRINS science target"></p>
<p><strong>Figure 6c. A science target corrected from the night calibration</strong> (LkCa 15, DCT 2018 frame 0059, air mass 1.32), compared with the pipeline’s <code>SPEC_DIVIDE_A0V</code>. Only one water scale and one velocity shift are fitted to the frame. Telluric imprint, measured as the slope of corrected flux against 1 − T, is −0.007 (H) and +0.001 (K) for tellurix against +0.077 and +0.025 for the A0V division. Continuum noise is 0.94% against 1.04% (H) and 0.54% against 0.67% (K). Caveat: this run predates the sequence-air-mass fix.</p>
<p><img src="figures/output/fig_igrins_coupling.png" class="img-fluid" style="width:100.0%" alt="K89 line coupling"></p>
<p><strong>Figure 6d. CO2 line coupling at the 2.0 µm band centre (K89).</strong> For the median frame, z_rms falls from 1.98 to 1.76 with first-order coupling. It improves in 10 of 10 frames (median 1.97 to 1.68), and the 10-frame mean residual’s rms falls from 1.49 to 1.22, while the CO2 column moves by only 0.0001. Uses first-exposure air masses and ERA5; both arms share them.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">7. Discussion</h2>
<p>Across three instruments, the residual left after a tellurix fit is mostly not telluric. On IGRINS it is the LSF shape and the detector; on the FTS atlases it is the stellar model. Better line physics therefore pays only once those are reduced, and the discussion should say so plainly.</p>
<p>Planned subsections:</p>
<ol type="1">
<li><strong>What limits a correction today.</strong>
<ul>
<li>IGRINS: the Gaussian LSF leaves about 3σ in deep cores, plus fringe and bad pixels at high S/N, and residuals grow about 1.4× from the driest night to the wettest.</li>
<li>FTS: Payne Zero line errors leave a ~1% floor (Section 5.3).</li>
</ul></li>
<li><strong>LBLRTM as a regression test, not the truth</strong> (<code>docs/validation.md</code>, “Beyond LBLRTM”). Line coupling helps the IGRINS 2.0 µm band centre and hurts its edges, where tellurix still matches LBLRTM, so LBLRTM shares that error. Propose a fixed scorecard of IGRINS night-bands, solar windows and column-consistency checks for judging physics options.</li>
<li><strong>Lessons that generalize.</strong>
<ul>
<li>A header air mass can masquerade as atmospheric physics (Section 6.3).</li>
<li>One spectrum’s anomaly can belong to that spectrum (the O2 B band, Section 5.3); a physics claim needs a second, independent spectrum.</li>
<li>Formal covariances understate errors 3–9× when the residual is stellar.</li>
</ul></li>
<li><strong>Other instruments.</strong> The core knows no instrument; a new one needs a reader, an LSF and an order rule. Name concrete next targets (open question: which ones? For example, IGRINS-2 on Gemini North, or other R ~ 40,000–100,000 NIR spectrographs).</li>
<li><strong>Future physics.</strong> Speed-dependent line shapes, HITRAN2020 against AER intensities, CO2 mixing beyond first order, a non-Gaussian IGRINS LSF, and a joint stellar–telluric fit through the shared gradient.</li>
</ol>
</section>
<section id="summary-software-and-data-availability" class="level2">
<h2 class="anchored" data-anchor-id="summary-software-and-data-availability">8. Summary; software and data availability</h2>
<p>The summary repeats the four results in one line each: speed (Section 3), LBLRTM agreement (Section 4), FTS atlases (Section 5) and IGRINS (Section 6).</p>
<p>AJ requires software and data citations. Planned statement:</p>
<ul>
<li><strong>Code:</strong> tellurix, tellurix-fts and tellurix-igrins, open source on GitHub. Cite a Zenodo DOI for the exact release used in the paper.</li>
<li><strong>Results:</strong> run records (HDF5), night calibrations and species scans, published as a release archive pinned by <code>data/results_manifest.json</code>. <code>results-2026-10-03</code> has DOI 10.5281/zenodo.23121557. The current release, <code>results-2026-10-05</code>, has a source-only Zenodo record (23156334) and needs its results tarball deposited.</li>
<li><strong>Inputs:</strong> AER Line File 3.9 and MT_CKD 4.3, downloaded with SHA-256 pins (<code>tellurix-download-data</code>); LBLRTM 12.17 used offline only; ERA5 (Copernicus, Hersbach et al.&nbsp;2020).</li>
<li><strong>Observations:</strong> the Arcturus atlas (Hinkle, Wallace &amp; Livingston 1995; ask in the README for a citation); NSO/Kitt Peak FTS data (required acknowledgement: “NSO/Kitt Peak FTS data used here were produced by NSF/NOAO”); IGRINS RRISA, with its citation and acknowledgement to be confirmed.</li>
<li><strong>Software cited:</strong> JAX, ExoJAX, NumPy, SciPy, h5py, Astropy if used. AJ’s <code>\software{}</code> block lists them.</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="index_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>