#!/usr/bin/env python
"""Extract LBLRTM 12.17's O2 collision-induced coefficient tables into tellurix.

Writes ``src/tellurix/_o2_cia_tables.py`` from the BLOCK DATA statements in
``contnm.f90``, asserting each table's length against its declared NPT. The
1.06 um term (O2INF2) is analytic in LBLRTM and is implemented as code in
``tellurix.o2_cia``, not tabulated here.

    uv run python scripts/extract_o2_cia.py
"""

from __future__ import annotations

import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/lblrtm/LBLRTM/src/contnm.f90"
OUTPUT = ROOT / "src/tellurix/_o2_cia_tables.py"
# block name -> (name in tellurix, what it is)
BLOCKS = {
    "bo2inf1": ("O2INF1", "1.27 um, Mate et al. 1999 (JGR 104, 30585); units 1/(amagat_O2 amagat_air)"),
    "bo2inf3": ("O2INF3", "A-band, Mlawer, from solar FTS measurements"),
    "bo2in_vis": ("O2_VIS", "visible O2-O2, Greenblatt et al. 1990 (JGR 95, 18577)"),
}
# A Fortran real: the visible table has a bare "0." among its exponents.
FLOAT = re.compile(r"[-+]?\d+\.\d*(?:[eE][-+]?\d+)?")


def block(text: str, name: str) -> tuple[tuple[float, float, float, int], list[float]]:
    start = text.index(f"BLOCK DATA {name}")
    end = text.index("end block data", start)
    # Comments can hold digits; a DATA statement never contains "!".
    body = "\n".join(line.split("!", 1)[0] for line in text[start:end].splitlines())
    header = re.search(r"DATA\s+V1,\s*V2,\s*DV,\s*NPT\s*/([^/]*)/", body)
    v1, v2, dv, npt = header.group(1).replace(",", " ").split()
    values = [float(x) for x in FLOAT.findall(body[header.end():])]
    if len(values) != int(npt):
        raise SystemExit(f"{name}: {len(values)} values against NPT {npt}")
    return (float(v1), float(v2), float(dv), int(npt)), values


def main() -> None:
    raw = SOURCE.read_bytes()
    text = raw.decode("latin-1")
    # AER's notice, verbatim from tellurix/mt_ckd.py, which carries it for the
    # same reason: this is derived from the continuum code distributed with LBLRTM.
    notice = [line for line in (ROOT / "src/tellurix/mt_ckd.py").read_text().splitlines()
              if line.startswith("#")][:8]
    if not notice[0].startswith("# Copyright"):
        raise SystemExit("could not find AER's notice in mt_ckd.py")
    lines = [
        *notice,
        "#",
        f"# Generated by scripts/extract_o2_cia.py from {SOURCE.name},",
        f"# sha256 {hashlib.sha256(raw).hexdigest()}. Do not edit.",
        '"""LBLRTM O2 collision-induced coefficient tables: (v1, v2, dv, npt) and values."""',
        "",
    ]
    for block_name, (name, about) in BLOCKS.items():
        (v1, v2, dv, npt), values = block(text, block_name)
        lines.append(f"# {about}")
        lines.append(f"{name}_GRID = ({v1!r}, {v2!r}, {dv!r}, {npt})")
        lines.append(f"{name} = (")
        for i in range(0, len(values), 6):
            lines.append("    " + ", ".join(f"{v:.4e}" for v in values[i:i + 6]) + ",")
        lines.append(")")
        lines.append("")
        print(f"{name}: {npt} values, {v1}-{v2} cm-1 every {dv}; max {max(values):.3e}")
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
