#!/usr/bin/env python
"""Build a hydrostatic layer profile CSV for an observing site and epoch.

The packaged ``example_midlatitude.csv`` is illustrative and carries present-day
trace-gas abundances. Retrievals that lean on a well-mixed species to break the
airmass degeneracy need the abundances of the epoch the data were taken in: CO2
rose from 357 ppm in 1993-94 to about 420 ppm, and that 17.6% error would map
one for one into the retrieved airmass.

The physics is ``tellurix.site_profile``; this is its command line.
"""

from __future__ import annotations

import argparse
import functools
from pathlib import Path

from tellurix.site_profile import (
    AFGL_MODELS, EPOCH_DRY_VMR, LAYERINGS, afgl_dry_vmr, build_site_profile,
    write_profile_csv,
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--surface-pressure-hpa", type=float, default=786.0)
    parser.add_argument("--surface-temperature-k", type=float, default=283.0)
    parser.add_argument("--site-altitude-km", type=float, default=2.096)
    parser.add_argument("--lapse-rate-k-km", type=float, default=6.5)
    parser.add_argument("--tropopause-temperature-k", type=float, default=216.65)
    parser.add_argument("--water-scale-height-km", type=float, default=2.0)
    parser.add_argument("--stratospheric-water-vmr", type=float, default=5.0e-6)
    parser.add_argument("--precipitable-water-mm", type=float, default=5.0)
    parser.add_argument("--epoch", choices=sorted(EPOCH_DRY_VMR), default="1994")
    parser.add_argument("--afgl-model", choices=AFGL_MODELS, default=None,
                        help="carry every AFGL molecule with its vertical structure, "
                             "instead of the handful of well-mixed surface values. A "
                             "species-scan can only rank what the profile knows about, "
                             "and a stratospheric gas cannot be described by one number: "
                             "ozone is 260x more abundant at 38 km than at the ground.")
    parser.add_argument("--layering", choices=LAYERINGS, default="weighted",
                        help="weighted: LBLRTM's air-weighted layer averages; centre: "
                             "sample each layer's centre, as profiles before 2026-10 were")
    parser.add_argument("--site", default="Kitt Peak")
    parser.add_argument("--output", type=Path, default=Path("data/profiles/kitt_peak_1994.csv"))
    args = parser.parse_args()

    # A function of altitude, so the builder can sample the AFGL gases at the
    # layer centres or average them across each layer, as --layering asks.
    dry_vmr = (EPOCH_DRY_VMR[args.epoch] if args.afgl_model is None
               else functools.partial(afgl_dry_vmr, args.afgl_model, epoch=args.epoch))

    profile = build_site_profile(
        args.surface_pressure_hpa,
        args.surface_temperature_k,
        args.site_altitude_km,
        args.lapse_rate_k_km,
        args.tropopause_temperature_k,
        args.water_scale_height_km,
        args.stratospheric_water_vmr,
        args.precipitable_water_mm,
        dry_vmr,
        layering=args.layering,
    )
    rows = write_profile_csv(args.output, profile, [
        f"{args.site}, {args.epoch} trace-gas abundances, generated by scripts/make_site_profile.py."
        + ("" if args.afgl_model is None else f" AFGL {args.afgl_model}."),
        f"surface {args.surface_pressure_hpa:.1f} hPa / {args.surface_temperature_k:.1f} K at "
        f"{args.site_altitude_km:.3f} km, lapse {args.lapse_rate_k_km:.1f} K/km.",
        f"water: exponential scale height {args.water_scale_height_km:.1f} km on a "
        f"{args.stratospheric_water_vmr:.1e} stratospheric floor, {args.precipitable_water_mm:.2f} mm vertical.",
        f"{args.layering} layers."
        + (" pressure_bar is each layer's air-weighted mean pressure." if args.layering == "weighted" else ""),
        "VMR columns are moist-air volume mixing ratios, dimensionless.",
    ])
    print(f"wrote {args.output} with {rows} layers")


if __name__ == "__main__":
    main()
